export const STYLES = {
  "drill-team": "Drill Team",
  contemporary: "Contemporary",
  "game-day": "Game Day",
  "hip-hop": "Hip Hop",
  jazz: "Jazz",
  acro: "Acro",
  ballet: "Ballet",
  ballroom: "Ballroom",
  breakdance: "Breakdance",
  commercial: "Commercial",
  kick: "Kick",
  lyrical: "Lyrical",
  majorette: "Majorette",
  military: "Military",
  open: "Open",
  other: "Other",
  pom: "Pom",
  tap: "Tap",
} as const;
