name: studio2stadium

services:
  db:
    image: postgres:18-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
  redis:
    image: redis:latest
    restart: always
    command:
      ["redis-server", "--save 20 1", "--loglevel warning"]
    ports:
      - "6379:6379"
    volumes:
      - cache:/data
  event-server:
    build:
      context: ./apps/events
      dockerfile: Dockerfile.dev
    volumes:
      - ./apps/events:/app
      - ./apps/events/cmd/.env:/app/cmd/.env
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  cache:
    driver: local
  pgdata:
