/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            isHealthy: boolean;
                            /** @enum {string} */
                            status: "ok" | "warning" | "error";
                            finishedAt: string;
                            debugInfo: {
                                pid: number;
                                ppid?: number;
                                uptime: number;
                                version: string;
                                platform: string;
                            };
                            checks: {
                                /** @enum {string} */
                                status: "ok" | "warning" | "error";
                                finishedAt: string;
                                isCached: boolean;
                                name: string;
                                message: string;
                                meta?: Record<string, never>;
                            }[];
                        };
                    };
                };
                /** @description Service Unavailable */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            isHealthy: boolean;
                            /** @enum {string} */
                            status: "ok" | "warning" | "error";
                            finishedAt: string;
                            debugInfo: {
                                pid: number;
                                ppid?: number;
                                uptime: number;
                                version: string;
                                platform: string;
                            };
                            checks: {
                                /** @enum {string} */
                                status: "ok" | "warning" | "error";
                                finishedAt: string;
                                isCached: boolean;
                                name: string;
                                message: string;
                                meta?: Record<string, never>;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create user account
         * @description Creates a new base user account.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        phone?: string | null;
                        email: string;
                        password: string;
                        /** @enum {string} */
                        accountType: "dancer" | "school";
                        confirmPassword: string;
                        username: string;
                        firstName: string;
                        lastName: string;
                        termsChecked: boolean;
                    };
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            email: string;
                            username: string;
                            firstName: string;
                            lastName: string;
                            phone: string | null;
                            id: string;
                            avatar: string | null;
                            displayEmail: string;
                            createdAt: string;
                            updatedAt: string | null;
                        };
                    };
                };
                /** @description Unprocessable Entity */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start user session
         * @description Logs in a user and creates a session in Redis.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        email: string;
                        password: string;
                    };
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": Record<string, never>;
                    };
                };
                /** @description Unprocessable Entity */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * End user session
         * @description Logs out the current user and deletes their session from Redis.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh user session
         * @description Refreshes the current user's session by bumping the Redis version.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get user session
         * @description Retrieves the current session's user information.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            email: string;
                            username: string;
                            /** @enum {string} */
                            type: "dancer" | "school";
                            platforms: ("core" | "prodigy")[];
                            id: string;
                            avatar: string | null;
                            displayEmail: string;
                            subscribed: boolean;
                            admin: ("core" | "prodigy") | null;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiError: {
            /** @description Human-readable error message suitable for display */
            message: string;
            /**
             * @description Machine-readable error code for programmatic handling
             * @example E_BAD_REQUEST
             */
            code: string;
            /**
             * @description HTTP status code returned by the server
             * @example 429
             */
            status: number;
            /** @description Additional context specific to the error type */
            meta?: {
                /**
                 * @description Seconds until the request can be retried
                 * @example 60
                 */
                retryAfter?: number;
                /**
                 * @description Validation error field name
                 * @example email
                 */
                field?: string;
                /**
                 * @description Validation error rule
                 * @example required
                 */
                rule?: string;
            };
        };
        ApiErrorResponse: {
            errors: components["schemas"]["ApiError"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
