/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AdminRouteRouteImport } from './routes/_admin/route'
import { Route as AccountRouteRouteImport } from './routes/_account/route'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AppTapInRouteImport } from './routes/_app/tap-in'
import { Route as AppExploreRouteImport } from './routes/_app/explore'
import { Route as AuthResetIndexRouteImport } from './routes/_auth/reset/index'
import { Route as AppEventsIndexRouteImport } from './routes/_app/events/index'
import { Route as AdminDashboardIndexRouteImport } from './routes/_admin/dashboard/index'
import { Route as AuthResetTokenIdRouteImport } from './routes/_auth/reset/$tokenId'
import { Route as AppRecruitingSubmitRouteImport } from './routes/_app/recruiting/submit'
import { Route as AppRecruitingSubmissionsRouteImport } from './routes/_app/recruiting/submissions'
import { Route as AppOnboardSubscriptionRouteImport } from './routes/_app/onboard/subscription'
import { Route as AppOnboardSchoolRouteImport } from './routes/_app/onboard/school'
import { Route as AppOnboardDancerRouteImport } from './routes/_app/onboard/dancer'
import { Route as AppEventsEventIdRouteImport } from './routes/_app/events/$eventId'
import { Route as AdminDashboardMetricsRouteImport } from './routes/_admin/dashboard/metrics'
import { Route as AccountAccountProfileRouteImport } from './routes/_account/account/profile'
import { Route as AccountAccountMediaRouteImport } from './routes/_account/account/media'
import { Route as AccountAccountGeneralRouteImport } from './routes/_account/account/general'
import { Route as AppprofilesSchoolUsernameRouteImport } from './routes/_app/(profiles)/school.$username'
import { Route as AppprofilesDancerUsernameRouteImport } from './routes/_app/(profiles)/dancer.$username'
import { Route as AdminDashboardAssetsUploadRouteImport } from './routes/_admin/dashboard/assets/upload'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRouteRoute = AccountRouteRouteImport.update({
  id: '/_account',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AppTapInRoute = AppTapInRouteImport.update({
  id: '/tap-in',
  path: '/tap-in',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppExploreRoute = AppExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => AppRouteRoute,
} as any)
const AuthResetIndexRoute = AuthResetIndexRouteImport.update({
  id: '/reset/',
  path: '/reset/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AppEventsIndexRoute = AppEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AdminDashboardIndexRoute = AdminDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AuthResetTokenIdRoute = AuthResetTokenIdRouteImport.update({
  id: '/reset/$tokenId',
  path: '/reset/$tokenId',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AppRecruitingSubmitRoute = AppRecruitingSubmitRouteImport.update({
  id: '/recruiting/submit',
  path: '/recruiting/submit',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppRecruitingSubmissionsRoute =
  AppRecruitingSubmissionsRouteImport.update({
    id: '/recruiting/submissions',
    path: '/recruiting/submissions',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppOnboardSubscriptionRoute = AppOnboardSubscriptionRouteImport.update({
  id: '/onboard/subscription',
  path: '/onboard/subscription',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOnboardSchoolRoute = AppOnboardSchoolRouteImport.update({
  id: '/onboard/school',
  path: '/onboard/school',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOnboardDancerRoute = AppOnboardDancerRouteImport.update({
  id: '/onboard/dancer',
  path: '/onboard/dancer',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppEventsEventIdRoute = AppEventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AdminDashboardMetricsRoute = AdminDashboardMetricsRouteImport.update({
  id: '/dashboard/metrics',
  path: '/dashboard/metrics',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AccountAccountProfileRoute = AccountAccountProfileRouteImport.update({
  id: '/account/profile',
  path: '/account/profile',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountAccountMediaRoute = AccountAccountMediaRouteImport.update({
  id: '/account/media',
  path: '/account/media',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountAccountGeneralRoute = AccountAccountGeneralRouteImport.update({
  id: '/account/general',
  path: '/account/general',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AppprofilesSchoolUsernameRoute =
  AppprofilesSchoolUsernameRouteImport.update({
    id: '/(profiles)/school/$username',
    path: '/school/$username',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppprofilesDancerUsernameRoute =
  AppprofilesDancerUsernameRouteImport.update({
    id: '/(profiles)/dancer/$username',
    path: '/dancer/$username',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AdminDashboardAssetsUploadRoute =
  AdminDashboardAssetsUploadRouteImport.update({
    id: '/dashboard/assets/upload',
    path: '/dashboard/assets/upload',
    getParentRoute: () => AdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/explore': typeof AppExploreRoute
  '/tap-in': typeof AppTapInRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/': typeof AppIndexRoute
  '/account/general': typeof AccountAccountGeneralRoute
  '/account/media': typeof AccountAccountMediaRoute
  '/account/profile': typeof AccountAccountProfileRoute
  '/dashboard/metrics': typeof AdminDashboardMetricsRoute
  '/events/$eventId': typeof AppEventsEventIdRoute
  '/onboard/dancer': typeof AppOnboardDancerRoute
  '/onboard/school': typeof AppOnboardSchoolRoute
  '/onboard/subscription': typeof AppOnboardSubscriptionRoute
  '/recruiting/submissions': typeof AppRecruitingSubmissionsRoute
  '/recruiting/submit': typeof AppRecruitingSubmitRoute
  '/reset/$tokenId': typeof AuthResetTokenIdRoute
  '/dashboard': typeof AdminDashboardIndexRoute
  '/events': typeof AppEventsIndexRoute
  '/reset': typeof AuthResetIndexRoute
  '/dashboard/assets/upload': typeof AdminDashboardAssetsUploadRoute
  '/dancer/$username': typeof AppprofilesDancerUsernameRoute
  '/school/$username': typeof AppprofilesSchoolUsernameRoute
}
export interface FileRoutesByTo {
  '/explore': typeof AppExploreRoute
  '/tap-in': typeof AppTapInRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/': typeof AppIndexRoute
  '/account/general': typeof AccountAccountGeneralRoute
  '/account/media': typeof AccountAccountMediaRoute
  '/account/profile': typeof AccountAccountProfileRoute
  '/dashboard/metrics': typeof AdminDashboardMetricsRoute
  '/events/$eventId': typeof AppEventsEventIdRoute
  '/onboard/dancer': typeof AppOnboardDancerRoute
  '/onboard/school': typeof AppOnboardSchoolRoute
  '/onboard/subscription': typeof AppOnboardSubscriptionRoute
  '/recruiting/submissions': typeof AppRecruitingSubmissionsRoute
  '/recruiting/submit': typeof AppRecruitingSubmitRoute
  '/reset/$tokenId': typeof AuthResetTokenIdRoute
  '/dashboard': typeof AdminDashboardIndexRoute
  '/events': typeof AppEventsIndexRoute
  '/reset': typeof AuthResetIndexRoute
  '/dashboard/assets/upload': typeof AdminDashboardAssetsUploadRoute
  '/dancer/$username': typeof AppprofilesDancerUsernameRoute
  '/school/$username': typeof AppprofilesSchoolUsernameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_account': typeof AccountRouteRouteWithChildren
  '/_admin': typeof AdminRouteRouteWithChildren
  '/_app': typeof AppRouteRouteWithChildren
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_app/explore': typeof AppExploreRoute
  '/_app/tap-in': typeof AppTapInRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_app/': typeof AppIndexRoute
  '/_account/account/general': typeof AccountAccountGeneralRoute
  '/_account/account/media': typeof AccountAccountMediaRoute
  '/_account/account/profile': typeof AccountAccountProfileRoute
  '/_admin/dashboard/metrics': typeof AdminDashboardMetricsRoute
  '/_app/events/$eventId': typeof AppEventsEventIdRoute
  '/_app/onboard/dancer': typeof AppOnboardDancerRoute
  '/_app/onboard/school': typeof AppOnboardSchoolRoute
  '/_app/onboard/subscription': typeof AppOnboardSubscriptionRoute
  '/_app/recruiting/submissions': typeof AppRecruitingSubmissionsRoute
  '/_app/recruiting/submit': typeof AppRecruitingSubmitRoute
  '/_auth/reset/$tokenId': typeof AuthResetTokenIdRoute
  '/_admin/dashboard/': typeof AdminDashboardIndexRoute
  '/_app/events/': typeof AppEventsIndexRoute
  '/_auth/reset/': typeof AuthResetIndexRoute
  '/_admin/dashboard/assets/upload': typeof AdminDashboardAssetsUploadRoute
  '/_app/(profiles)/dancer/$username': typeof AppprofilesDancerUsernameRoute
  '/_app/(profiles)/school/$username': typeof AppprofilesSchoolUsernameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/explore'
    | '/tap-in'
    | '/login'
    | '/signup'
    | '/'
    | '/account/general'
    | '/account/media'
    | '/account/profile'
    | '/dashboard/metrics'
    | '/events/$eventId'
    | '/onboard/dancer'
    | '/onboard/school'
    | '/onboard/subscription'
    | '/recruiting/submissions'
    | '/recruiting/submit'
    | '/reset/$tokenId'
    | '/dashboard'
    | '/events'
    | '/reset'
    | '/dashboard/assets/upload'
    | '/dancer/$username'
    | '/school/$username'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/explore'
    | '/tap-in'
    | '/login'
    | '/signup'
    | '/'
    | '/account/general'
    | '/account/media'
    | '/account/profile'
    | '/dashboard/metrics'
    | '/events/$eventId'
    | '/onboard/dancer'
    | '/onboard/school'
    | '/onboard/subscription'
    | '/recruiting/submissions'
    | '/recruiting/submit'
    | '/reset/$tokenId'
    | '/dashboard'
    | '/events'
    | '/reset'
    | '/dashboard/assets/upload'
    | '/dancer/$username'
    | '/school/$username'
  id:
    | '__root__'
    | '/_account'
    | '/_admin'
    | '/_app'
    | '/_auth'
    | '/_app/explore'
    | '/_app/tap-in'
    | '/_auth/login'
    | '/_auth/signup'
    | '/_app/'
    | '/_account/account/general'
    | '/_account/account/media'
    | '/_account/account/profile'
    | '/_admin/dashboard/metrics'
    | '/_app/events/$eventId'
    | '/_app/onboard/dancer'
    | '/_app/onboard/school'
    | '/_app/onboard/subscription'
    | '/_app/recruiting/submissions'
    | '/_app/recruiting/submit'
    | '/_auth/reset/$tokenId'
    | '/_admin/dashboard/'
    | '/_app/events/'
    | '/_auth/reset/'
    | '/_admin/dashboard/assets/upload'
    | '/_app/(profiles)/dancer/$username'
    | '/_app/(profiles)/school/$username'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AccountRouteRoute: typeof AccountRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_account': {
      id: '/_account'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AccountRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_app/tap-in': {
      id: '/_app/tap-in'
      path: '/tap-in'
      fullPath: '/tap-in'
      preLoaderRoute: typeof AppTapInRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/explore': {
      id: '/_app/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof AppExploreRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_auth/reset/': {
      id: '/_auth/reset/'
      path: '/reset'
      fullPath: '/reset'
      preLoaderRoute: typeof AuthResetIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_app/events/': {
      id: '/_app/events/'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof AppEventsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_admin/dashboard/': {
      id: '/_admin/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AdminDashboardIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_auth/reset/$tokenId': {
      id: '/_auth/reset/$tokenId'
      path: '/reset/$tokenId'
      fullPath: '/reset/$tokenId'
      preLoaderRoute: typeof AuthResetTokenIdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_app/recruiting/submit': {
      id: '/_app/recruiting/submit'
      path: '/recruiting/submit'
      fullPath: '/recruiting/submit'
      preLoaderRoute: typeof AppRecruitingSubmitRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/recruiting/submissions': {
      id: '/_app/recruiting/submissions'
      path: '/recruiting/submissions'
      fullPath: '/recruiting/submissions'
      preLoaderRoute: typeof AppRecruitingSubmissionsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/onboard/subscription': {
      id: '/_app/onboard/subscription'
      path: '/onboard/subscription'
      fullPath: '/onboard/subscription'
      preLoaderRoute: typeof AppOnboardSubscriptionRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/onboard/school': {
      id: '/_app/onboard/school'
      path: '/onboard/school'
      fullPath: '/onboard/school'
      preLoaderRoute: typeof AppOnboardSchoolRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/onboard/dancer': {
      id: '/_app/onboard/dancer'
      path: '/onboard/dancer'
      fullPath: '/onboard/dancer'
      preLoaderRoute: typeof AppOnboardDancerRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/events/$eventId': {
      id: '/_app/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof AppEventsEventIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_admin/dashboard/metrics': {
      id: '/_admin/dashboard/metrics'
      path: '/dashboard/metrics'
      fullPath: '/dashboard/metrics'
      preLoaderRoute: typeof AdminDashboardMetricsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_account/account/profile': {
      id: '/_account/account/profile'
      path: '/account/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof AccountAccountProfileRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/_account/account/media': {
      id: '/_account/account/media'
      path: '/account/media'
      fullPath: '/account/media'
      preLoaderRoute: typeof AccountAccountMediaRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/_account/account/general': {
      id: '/_account/account/general'
      path: '/account/general'
      fullPath: '/account/general'
      preLoaderRoute: typeof AccountAccountGeneralRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/_app/(profiles)/school/$username': {
      id: '/_app/(profiles)/school/$username'
      path: '/school/$username'
      fullPath: '/school/$username'
      preLoaderRoute: typeof AppprofilesSchoolUsernameRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/(profiles)/dancer/$username': {
      id: '/_app/(profiles)/dancer/$username'
      path: '/dancer/$username'
      fullPath: '/dancer/$username'
      preLoaderRoute: typeof AppprofilesDancerUsernameRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_admin/dashboard/assets/upload': {
      id: '/_admin/dashboard/assets/upload'
      path: '/dashboard/assets/upload'
      fullPath: '/dashboard/assets/upload'
      preLoaderRoute: typeof AdminDashboardAssetsUploadRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AccountRouteRouteChildren {
  AccountAccountGeneralRoute: typeof AccountAccountGeneralRoute
  AccountAccountMediaRoute: typeof AccountAccountMediaRoute
  AccountAccountProfileRoute: typeof AccountAccountProfileRoute
}

const AccountRouteRouteChildren: AccountRouteRouteChildren = {
  AccountAccountGeneralRoute: AccountAccountGeneralRoute,
  AccountAccountMediaRoute: AccountAccountMediaRoute,
  AccountAccountProfileRoute: AccountAccountProfileRoute,
}

const AccountRouteRouteWithChildren = AccountRouteRoute._addFileChildren(
  AccountRouteRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminDashboardMetricsRoute: typeof AdminDashboardMetricsRoute
  AdminDashboardIndexRoute: typeof AdminDashboardIndexRoute
  AdminDashboardAssetsUploadRoute: typeof AdminDashboardAssetsUploadRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminDashboardMetricsRoute: AdminDashboardMetricsRoute,
  AdminDashboardIndexRoute: AdminDashboardIndexRoute,
  AdminDashboardAssetsUploadRoute: AdminDashboardAssetsUploadRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppExploreRoute: typeof AppExploreRoute
  AppTapInRoute: typeof AppTapInRoute
  AppIndexRoute: typeof AppIndexRoute
  AppEventsEventIdRoute: typeof AppEventsEventIdRoute
  AppOnboardDancerRoute: typeof AppOnboardDancerRoute
  AppOnboardSchoolRoute: typeof AppOnboardSchoolRoute
  AppOnboardSubscriptionRoute: typeof AppOnboardSubscriptionRoute
  AppRecruitingSubmissionsRoute: typeof AppRecruitingSubmissionsRoute
  AppRecruitingSubmitRoute: typeof AppRecruitingSubmitRoute
  AppEventsIndexRoute: typeof AppEventsIndexRoute
  AppprofilesDancerUsernameRoute: typeof AppprofilesDancerUsernameRoute
  AppprofilesSchoolUsernameRoute: typeof AppprofilesSchoolUsernameRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppExploreRoute: AppExploreRoute,
  AppTapInRoute: AppTapInRoute,
  AppIndexRoute: AppIndexRoute,
  AppEventsEventIdRoute: AppEventsEventIdRoute,
  AppOnboardDancerRoute: AppOnboardDancerRoute,
  AppOnboardSchoolRoute: AppOnboardSchoolRoute,
  AppOnboardSubscriptionRoute: AppOnboardSubscriptionRoute,
  AppRecruitingSubmissionsRoute: AppRecruitingSubmissionsRoute,
  AppRecruitingSubmitRoute: AppRecruitingSubmitRoute,
  AppEventsIndexRoute: AppEventsIndexRoute,
  AppprofilesDancerUsernameRoute: AppprofilesDancerUsernameRoute,
  AppprofilesSchoolUsernameRoute: AppprofilesSchoolUsernameRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthResetTokenIdRoute: typeof AuthResetTokenIdRoute
  AuthResetIndexRoute: typeof AuthResetIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthResetTokenIdRoute: AuthResetTokenIdRoute,
  AuthResetIndexRoute: AuthResetIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AccountRouteRoute: AccountRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
