/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteRouteImport } from './routes/_settings/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AdminRouteRouteImport } from './routes/_admin/route'
import { Route as ApproutesIndexRouteImport } from './routes/_app/(routes)/index'
import { Route as AuthroutesSignupRouteImport } from './routes/_auth/(routes)/signup'
import { Route as AuthroutesLoginRouteImport } from './routes/_auth/(routes)/login'
import { Route as ApproutesPlaygroundRouteImport } from './routes/_app/(routes)/playground'
import { Route as ApproutesLibraryRouteImport } from './routes/_app/(routes)/library'
import { Route as ApproutesExploreRouteImport } from './routes/_app/(routes)/explore'
import { Route as AuthroutesResetIndexRouteImport } from './routes/_auth/(routes)/reset/index'
import { Route as ApproutesEventsIndexRouteImport } from './routes/_app/(routes)/events/index'
import { Route as AdminroutesDashboardIndexRouteImport } from './routes/_admin/(routes)/dashboard/index'
import { Route as SettingsroutesSettingsProfileRouteImport } from './routes/_settings/(routes)/settings/profile'
import { Route as SettingsroutesSettingsMediaRouteImport } from './routes/_settings/(routes)/settings/media'
import { Route as SettingsroutesSettingsGeneralRouteImport } from './routes/_settings/(routes)/settings/general'
import { Route as AuthroutesResetTokenIdRouteImport } from './routes/_auth/(routes)/reset/$tokenId'
import { Route as ApproutesOnboardingSubscriptionRouteImport } from './routes/_app/(routes)/onboarding/subscription'
import { Route as ApproutesOnboardingSchoolRouteImport } from './routes/_app/(routes)/onboarding/school'
import { Route as ApproutesOnboardingDancerRouteImport } from './routes/_app/(routes)/onboarding/dancer'
import { Route as ApproutesEventsEventIdRouteImport } from './routes/_app/(routes)/events/$eventId'
import { Route as AdminroutesDashboardMetricsRouteImport } from './routes/_admin/(routes)/dashboard/metrics'
import { Route as ApproutesUUsernameIndexRouteImport } from './routes/_app/(routes)/u/$username/index'
import { Route as ApproutesUUsernameRecruitingRouteImport } from './routes/_app/(routes)/u/$username/recruiting'
import { Route as AdminroutesDashboardAssetsUploadRouteImport } from './routes/_admin/(routes)/dashboard/assets/upload'

const SettingsRouteRoute = SettingsRouteRouteImport.update({
  id: '/_settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApproutesIndexRoute = ApproutesIndexRouteImport.update({
  id: '/(routes)/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AuthroutesSignupRoute = AuthroutesSignupRouteImport.update({
  id: '/(routes)/signup',
  path: '/signup',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthroutesLoginRoute = AuthroutesLoginRouteImport.update({
  id: '/(routes)/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ApproutesPlaygroundRoute = ApproutesPlaygroundRouteImport.update({
  id: '/(routes)/playground',
  path: '/playground',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApproutesLibraryRoute = ApproutesLibraryRouteImport.update({
  id: '/(routes)/library',
  path: '/library',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApproutesExploreRoute = ApproutesExploreRouteImport.update({
  id: '/(routes)/explore',
  path: '/explore',
  getParentRoute: () => AppRouteRoute,
} as any)
const AuthroutesResetIndexRoute = AuthroutesResetIndexRouteImport.update({
  id: '/(routes)/reset/',
  path: '/reset/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ApproutesEventsIndexRoute = ApproutesEventsIndexRouteImport.update({
  id: '/(routes)/events/',
  path: '/events/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AdminroutesDashboardIndexRoute =
  AdminroutesDashboardIndexRouteImport.update({
    id: '/(routes)/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const SettingsroutesSettingsProfileRoute =
  SettingsroutesSettingsProfileRouteImport.update({
    id: '/(routes)/settings/profile',
    path: '/settings/profile',
    getParentRoute: () => SettingsRouteRoute,
  } as any)
const SettingsroutesSettingsMediaRoute =
  SettingsroutesSettingsMediaRouteImport.update({
    id: '/(routes)/settings/media',
    path: '/settings/media',
    getParentRoute: () => SettingsRouteRoute,
  } as any)
const SettingsroutesSettingsGeneralRoute =
  SettingsroutesSettingsGeneralRouteImport.update({
    id: '/(routes)/settings/general',
    path: '/settings/general',
    getParentRoute: () => SettingsRouteRoute,
  } as any)
const AuthroutesResetTokenIdRoute = AuthroutesResetTokenIdRouteImport.update({
  id: '/(routes)/reset/$tokenId',
  path: '/reset/$tokenId',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ApproutesOnboardingSubscriptionRoute =
  ApproutesOnboardingSubscriptionRouteImport.update({
    id: '/(routes)/onboarding/subscription',
    path: '/onboarding/subscription',
    getParentRoute: () => AppRouteRoute,
  } as any)
const ApproutesOnboardingSchoolRoute =
  ApproutesOnboardingSchoolRouteImport.update({
    id: '/(routes)/onboarding/school',
    path: '/onboarding/school',
    getParentRoute: () => AppRouteRoute,
  } as any)
const ApproutesOnboardingDancerRoute =
  ApproutesOnboardingDancerRouteImport.update({
    id: '/(routes)/onboarding/dancer',
    path: '/onboarding/dancer',
    getParentRoute: () => AppRouteRoute,
  } as any)
const ApproutesEventsEventIdRoute = ApproutesEventsEventIdRouteImport.update({
  id: '/(routes)/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AdminroutesDashboardMetricsRoute =
  AdminroutesDashboardMetricsRouteImport.update({
    id: '/(routes)/dashboard/metrics',
    path: '/dashboard/metrics',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const ApproutesUUsernameIndexRoute = ApproutesUUsernameIndexRouteImport.update({
  id: '/(routes)/u/$username/',
  path: '/u/$username/',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApproutesUUsernameRecruitingRoute =
  ApproutesUUsernameRecruitingRouteImport.update({
    id: '/(routes)/u/$username/recruiting',
    path: '/u/$username/recruiting',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AdminroutesDashboardAssetsUploadRoute =
  AdminroutesDashboardAssetsUploadRouteImport.update({
    id: '/(routes)/dashboard/assets/upload',
    path: '/dashboard/assets/upload',
    getParentRoute: () => AdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ApproutesIndexRoute
  '/explore': typeof ApproutesExploreRoute
  '/library': typeof ApproutesLibraryRoute
  '/playground': typeof ApproutesPlaygroundRoute
  '/login': typeof AuthroutesLoginRoute
  '/signup': typeof AuthroutesSignupRoute
  '/dashboard/metrics': typeof AdminroutesDashboardMetricsRoute
  '/events/$eventId': typeof ApproutesEventsEventIdRoute
  '/onboarding/dancer': typeof ApproutesOnboardingDancerRoute
  '/onboarding/school': typeof ApproutesOnboardingSchoolRoute
  '/onboarding/subscription': typeof ApproutesOnboardingSubscriptionRoute
  '/reset/$tokenId': typeof AuthroutesResetTokenIdRoute
  '/settings/general': typeof SettingsroutesSettingsGeneralRoute
  '/settings/media': typeof SettingsroutesSettingsMediaRoute
  '/settings/profile': typeof SettingsroutesSettingsProfileRoute
  '/dashboard/': typeof AdminroutesDashboardIndexRoute
  '/events/': typeof ApproutesEventsIndexRoute
  '/reset/': typeof AuthroutesResetIndexRoute
  '/dashboard/assets/upload': typeof AdminroutesDashboardAssetsUploadRoute
  '/u/$username/recruiting': typeof ApproutesUUsernameRecruitingRoute
  '/u/$username/': typeof ApproutesUUsernameIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof ApproutesIndexRoute
  '/explore': typeof ApproutesExploreRoute
  '/library': typeof ApproutesLibraryRoute
  '/playground': typeof ApproutesPlaygroundRoute
  '/login': typeof AuthroutesLoginRoute
  '/signup': typeof AuthroutesSignupRoute
  '/dashboard/metrics': typeof AdminroutesDashboardMetricsRoute
  '/events/$eventId': typeof ApproutesEventsEventIdRoute
  '/onboarding/dancer': typeof ApproutesOnboardingDancerRoute
  '/onboarding/school': typeof ApproutesOnboardingSchoolRoute
  '/onboarding/subscription': typeof ApproutesOnboardingSubscriptionRoute
  '/reset/$tokenId': typeof AuthroutesResetTokenIdRoute
  '/settings/general': typeof SettingsroutesSettingsGeneralRoute
  '/settings/media': typeof SettingsroutesSettingsMediaRoute
  '/settings/profile': typeof SettingsroutesSettingsProfileRoute
  '/dashboard': typeof AdminroutesDashboardIndexRoute
  '/events': typeof ApproutesEventsIndexRoute
  '/reset': typeof AuthroutesResetIndexRoute
  '/dashboard/assets/upload': typeof AdminroutesDashboardAssetsUploadRoute
  '/u/$username/recruiting': typeof ApproutesUUsernameRecruitingRoute
  '/u/$username': typeof ApproutesUUsernameIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_admin': typeof AdminRouteRouteWithChildren
  '/_app': typeof AppRouteRouteWithChildren
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_settings': typeof SettingsRouteRouteWithChildren
  '/_app/(routes)/explore': typeof ApproutesExploreRoute
  '/_app/(routes)/library': typeof ApproutesLibraryRoute
  '/_app/(routes)/playground': typeof ApproutesPlaygroundRoute
  '/_auth/(routes)/login': typeof AuthroutesLoginRoute
  '/_auth/(routes)/signup': typeof AuthroutesSignupRoute
  '/_app/(routes)/': typeof ApproutesIndexRoute
  '/_admin/(routes)/dashboard/metrics': typeof AdminroutesDashboardMetricsRoute
  '/_app/(routes)/events/$eventId': typeof ApproutesEventsEventIdRoute
  '/_app/(routes)/onboarding/dancer': typeof ApproutesOnboardingDancerRoute
  '/_app/(routes)/onboarding/school': typeof ApproutesOnboardingSchoolRoute
  '/_app/(routes)/onboarding/subscription': typeof ApproutesOnboardingSubscriptionRoute
  '/_auth/(routes)/reset/$tokenId': typeof AuthroutesResetTokenIdRoute
  '/_settings/(routes)/settings/general': typeof SettingsroutesSettingsGeneralRoute
  '/_settings/(routes)/settings/media': typeof SettingsroutesSettingsMediaRoute
  '/_settings/(routes)/settings/profile': typeof SettingsroutesSettingsProfileRoute
  '/_admin/(routes)/dashboard/': typeof AdminroutesDashboardIndexRoute
  '/_app/(routes)/events/': typeof ApproutesEventsIndexRoute
  '/_auth/(routes)/reset/': typeof AuthroutesResetIndexRoute
  '/_admin/(routes)/dashboard/assets/upload': typeof AdminroutesDashboardAssetsUploadRoute
  '/_app/(routes)/u/$username/recruiting': typeof ApproutesUUsernameRecruitingRoute
  '/_app/(routes)/u/$username/': typeof ApproutesUUsernameIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/explore'
    | '/library'
    | '/playground'
    | '/login'
    | '/signup'
    | '/dashboard/metrics'
    | '/events/$eventId'
    | '/onboarding/dancer'
    | '/onboarding/school'
    | '/onboarding/subscription'
    | '/reset/$tokenId'
    | '/settings/general'
    | '/settings/media'
    | '/settings/profile'
    | '/dashboard/'
    | '/events/'
    | '/reset/'
    | '/dashboard/assets/upload'
    | '/u/$username/recruiting'
    | '/u/$username/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/explore'
    | '/library'
    | '/playground'
    | '/login'
    | '/signup'
    | '/dashboard/metrics'
    | '/events/$eventId'
    | '/onboarding/dancer'
    | '/onboarding/school'
    | '/onboarding/subscription'
    | '/reset/$tokenId'
    | '/settings/general'
    | '/settings/media'
    | '/settings/profile'
    | '/dashboard'
    | '/events'
    | '/reset'
    | '/dashboard/assets/upload'
    | '/u/$username/recruiting'
    | '/u/$username'
  id:
    | '__root__'
    | '/_admin'
    | '/_app'
    | '/_auth'
    | '/_settings'
    | '/_app/(routes)/explore'
    | '/_app/(routes)/library'
    | '/_app/(routes)/playground'
    | '/_auth/(routes)/login'
    | '/_auth/(routes)/signup'
    | '/_app/(routes)/'
    | '/_admin/(routes)/dashboard/metrics'
    | '/_app/(routes)/events/$eventId'
    | '/_app/(routes)/onboarding/dancer'
    | '/_app/(routes)/onboarding/school'
    | '/_app/(routes)/onboarding/subscription'
    | '/_auth/(routes)/reset/$tokenId'
    | '/_settings/(routes)/settings/general'
    | '/_settings/(routes)/settings/media'
    | '/_settings/(routes)/settings/profile'
    | '/_admin/(routes)/dashboard/'
    | '/_app/(routes)/events/'
    | '/_auth/(routes)/reset/'
    | '/_admin/(routes)/dashboard/assets/upload'
    | '/_app/(routes)/u/$username/recruiting'
    | '/_app/(routes)/u/$username/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  SettingsRouteRoute: typeof SettingsRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_settings': {
      id: '/_settings'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SettingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/(routes)/': {
      id: '/_app/(routes)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ApproutesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_auth/(routes)/signup': {
      id: '/_auth/(routes)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthroutesSignupRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/(routes)/login': {
      id: '/_auth/(routes)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthroutesLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_app/(routes)/playground': {
      id: '/_app/(routes)/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof ApproutesPlaygroundRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/(routes)/library': {
      id: '/_app/(routes)/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof ApproutesLibraryRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/(routes)/explore': {
      id: '/_app/(routes)/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ApproutesExploreRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_auth/(routes)/reset/': {
      id: '/_auth/(routes)/reset/'
      path: '/reset'
      fullPath: '/reset/'
      preLoaderRoute: typeof AuthroutesResetIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_app/(routes)/events/': {
      id: '/_app/(routes)/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof ApproutesEventsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_admin/(routes)/dashboard/': {
      id: '/_admin/(routes)/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AdminroutesDashboardIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_settings/(routes)/settings/profile': {
      id: '/_settings/(routes)/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsroutesSettingsProfileRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/_settings/(routes)/settings/media': {
      id: '/_settings/(routes)/settings/media'
      path: '/settings/media'
      fullPath: '/settings/media'
      preLoaderRoute: typeof SettingsroutesSettingsMediaRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/_settings/(routes)/settings/general': {
      id: '/_settings/(routes)/settings/general'
      path: '/settings/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof SettingsroutesSettingsGeneralRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/_auth/(routes)/reset/$tokenId': {
      id: '/_auth/(routes)/reset/$tokenId'
      path: '/reset/$tokenId'
      fullPath: '/reset/$tokenId'
      preLoaderRoute: typeof AuthroutesResetTokenIdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_app/(routes)/onboarding/subscription': {
      id: '/_app/(routes)/onboarding/subscription'
      path: '/onboarding/subscription'
      fullPath: '/onboarding/subscription'
      preLoaderRoute: typeof ApproutesOnboardingSubscriptionRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/(routes)/onboarding/school': {
      id: '/_app/(routes)/onboarding/school'
      path: '/onboarding/school'
      fullPath: '/onboarding/school'
      preLoaderRoute: typeof ApproutesOnboardingSchoolRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/(routes)/onboarding/dancer': {
      id: '/_app/(routes)/onboarding/dancer'
      path: '/onboarding/dancer'
      fullPath: '/onboarding/dancer'
      preLoaderRoute: typeof ApproutesOnboardingDancerRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/(routes)/events/$eventId': {
      id: '/_app/(routes)/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof ApproutesEventsEventIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_admin/(routes)/dashboard/metrics': {
      id: '/_admin/(routes)/dashboard/metrics'
      path: '/dashboard/metrics'
      fullPath: '/dashboard/metrics'
      preLoaderRoute: typeof AdminroutesDashboardMetricsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_app/(routes)/u/$username/': {
      id: '/_app/(routes)/u/$username/'
      path: '/u/$username'
      fullPath: '/u/$username/'
      preLoaderRoute: typeof ApproutesUUsernameIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/(routes)/u/$username/recruiting': {
      id: '/_app/(routes)/u/$username/recruiting'
      path: '/u/$username/recruiting'
      fullPath: '/u/$username/recruiting'
      preLoaderRoute: typeof ApproutesUUsernameRecruitingRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_admin/(routes)/dashboard/assets/upload': {
      id: '/_admin/(routes)/dashboard/assets/upload'
      path: '/dashboard/assets/upload'
      fullPath: '/dashboard/assets/upload'
      preLoaderRoute: typeof AdminroutesDashboardAssetsUploadRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminroutesDashboardMetricsRoute: typeof AdminroutesDashboardMetricsRoute
  AdminroutesDashboardIndexRoute: typeof AdminroutesDashboardIndexRoute
  AdminroutesDashboardAssetsUploadRoute: typeof AdminroutesDashboardAssetsUploadRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminroutesDashboardMetricsRoute: AdminroutesDashboardMetricsRoute,
  AdminroutesDashboardIndexRoute: AdminroutesDashboardIndexRoute,
  AdminroutesDashboardAssetsUploadRoute: AdminroutesDashboardAssetsUploadRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface AppRouteRouteChildren {
  ApproutesExploreRoute: typeof ApproutesExploreRoute
  ApproutesLibraryRoute: typeof ApproutesLibraryRoute
  ApproutesPlaygroundRoute: typeof ApproutesPlaygroundRoute
  ApproutesIndexRoute: typeof ApproutesIndexRoute
  ApproutesEventsEventIdRoute: typeof ApproutesEventsEventIdRoute
  ApproutesOnboardingDancerRoute: typeof ApproutesOnboardingDancerRoute
  ApproutesOnboardingSchoolRoute: typeof ApproutesOnboardingSchoolRoute
  ApproutesOnboardingSubscriptionRoute: typeof ApproutesOnboardingSubscriptionRoute
  ApproutesEventsIndexRoute: typeof ApproutesEventsIndexRoute
  ApproutesUUsernameRecruitingRoute: typeof ApproutesUUsernameRecruitingRoute
  ApproutesUUsernameIndexRoute: typeof ApproutesUUsernameIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  ApproutesExploreRoute: ApproutesExploreRoute,
  ApproutesLibraryRoute: ApproutesLibraryRoute,
  ApproutesPlaygroundRoute: ApproutesPlaygroundRoute,
  ApproutesIndexRoute: ApproutesIndexRoute,
  ApproutesEventsEventIdRoute: ApproutesEventsEventIdRoute,
  ApproutesOnboardingDancerRoute: ApproutesOnboardingDancerRoute,
  ApproutesOnboardingSchoolRoute: ApproutesOnboardingSchoolRoute,
  ApproutesOnboardingSubscriptionRoute: ApproutesOnboardingSubscriptionRoute,
  ApproutesEventsIndexRoute: ApproutesEventsIndexRoute,
  ApproutesUUsernameRecruitingRoute: ApproutesUUsernameRecruitingRoute,
  ApproutesUUsernameIndexRoute: ApproutesUUsernameIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthroutesLoginRoute: typeof AuthroutesLoginRoute
  AuthroutesSignupRoute: typeof AuthroutesSignupRoute
  AuthroutesResetTokenIdRoute: typeof AuthroutesResetTokenIdRoute
  AuthroutesResetIndexRoute: typeof AuthroutesResetIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthroutesLoginRoute: AuthroutesLoginRoute,
  AuthroutesSignupRoute: AuthroutesSignupRoute,
  AuthroutesResetTokenIdRoute: AuthroutesResetTokenIdRoute,
  AuthroutesResetIndexRoute: AuthroutesResetIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface SettingsRouteRouteChildren {
  SettingsroutesSettingsGeneralRoute: typeof SettingsroutesSettingsGeneralRoute
  SettingsroutesSettingsMediaRoute: typeof SettingsroutesSettingsMediaRoute
  SettingsroutesSettingsProfileRoute: typeof SettingsroutesSettingsProfileRoute
}

const SettingsRouteRouteChildren: SettingsRouteRouteChildren = {
  SettingsroutesSettingsGeneralRoute: SettingsroutesSettingsGeneralRoute,
  SettingsroutesSettingsMediaRoute: SettingsroutesSettingsMediaRoute,
  SettingsroutesSettingsProfileRoute: SettingsroutesSettingsProfileRoute,
}

const SettingsRouteRouteWithChildren = SettingsRouteRoute._addFileChildren(
  SettingsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  SettingsRouteRoute: SettingsRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
