/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteRouteImport } from './routes/_settings/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AdminRouteRouteImport } from './routes/_admin/route'
import { Route as ApproutesIndexRouteImport } from './routes/_app/(routes)/index'
import { Route as SettingsroutesSettingsRouteImport } from './routes/_settings/(routes)/settings'
import { Route as AuthroutesSignupRouteImport } from './routes/_auth/(routes)/signup'
import { Route as AuthroutesResetRouteImport } from './routes/_auth/(routes)/reset'
import { Route as AuthroutesLoginRouteImport } from './routes/_auth/(routes)/login'
import { Route as ApproutesUnauthorizedRouteImport } from './routes/_app/(routes)/unauthorized'
import { Route as ApproutesSessionRouteImport } from './routes/_app/(routes)/session'
import { Route as ApproutesResourcesRouteImport } from './routes/_app/(routes)/resources'
import { Route as ApproutesExploreRouteImport } from './routes/_app/(routes)/explore'
import { Route as ApproutesEventsRouteImport } from './routes/_app/(routes)/events'
import { Route as AdminroutesDashboardRouteImport } from './routes/_admin/(routes)/dashboard'
import { Route as SettingsroutesSettingsProfileRouteImport } from './routes/_settings/(routes)/settings/profile'
import { Route as SettingsroutesSettingsMediaRouteImport } from './routes/_settings/(routes)/settings/media'
import { Route as SettingsroutesSettingsGeneralRouteImport } from './routes/_settings/(routes)/settings/general'
import { Route as AuthroutesResetTokenIdRouteImport } from './routes/_auth/(routes)/reset/$tokenId'
import { Route as ApproutesOnboardingSubscriptionRouteImport } from './routes/_app/(routes)/onboarding/subscription'
import { Route as ApproutesOnboardingSchoolRouteImport } from './routes/_app/(routes)/onboarding/school'
import { Route as ApproutesOnboardingDancerRouteImport } from './routes/_app/(routes)/onboarding/dancer'
import { Route as ApproutesEventsEventIdRouteImport } from './routes/_app/(routes)/events/$eventId'
import { Route as AdminroutesDashboardMetricsRouteImport } from './routes/_admin/(routes)/dashboard/metrics'
import { Route as AdminroutesDashboardAssetsRouteImport } from './routes/_admin/(routes)/dashboard/assets'
import { Route as ApproutesUUsernameIndexRouteImport } from './routes/_app/(routes)/u/$username/index'
import { Route as ApproutesSchoolUsernameIndexRouteImport } from './routes/_app/(routes)/school/$username/index'
import { Route as ApproutesUUsernameRecruitingRouteImport } from './routes/_app/(routes)/u/$username/recruiting'
import { Route as ApproutesSchoolUsernameRecruitingRouteImport } from './routes/_app/(routes)/school/$username/recruiting'

const SettingsRouteRoute = SettingsRouteRouteImport.update({
  id: '/_settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApproutesIndexRoute = ApproutesIndexRouteImport.update({
  id: '/(routes)/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const SettingsroutesSettingsRoute = SettingsroutesSettingsRouteImport.update({
  id: '/(routes)/settings',
  path: '/settings',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const AuthroutesSignupRoute = AuthroutesSignupRouteImport.update({
  id: '/(routes)/signup',
  path: '/signup',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthroutesResetRoute = AuthroutesResetRouteImport.update({
  id: '/(routes)/reset',
  path: '/reset',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthroutesLoginRoute = AuthroutesLoginRouteImport.update({
  id: '/(routes)/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ApproutesUnauthorizedRoute = ApproutesUnauthorizedRouteImport.update({
  id: '/(routes)/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApproutesSessionRoute = ApproutesSessionRouteImport.update({
  id: '/(routes)/session',
  path: '/session',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApproutesResourcesRoute = ApproutesResourcesRouteImport.update({
  id: '/(routes)/resources',
  path: '/resources',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApproutesExploreRoute = ApproutesExploreRouteImport.update({
  id: '/(routes)/explore',
  path: '/explore',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApproutesEventsRoute = ApproutesEventsRouteImport.update({
  id: '/(routes)/events',
  path: '/events',
  getParentRoute: () => AppRouteRoute,
} as any)
const AdminroutesDashboardRoute = AdminroutesDashboardRouteImport.update({
  id: '/(routes)/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRouteRoute,
} as any)
const SettingsroutesSettingsProfileRoute =
  SettingsroutesSettingsProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => SettingsroutesSettingsRoute,
  } as any)
const SettingsroutesSettingsMediaRoute =
  SettingsroutesSettingsMediaRouteImport.update({
    id: '/media',
    path: '/media',
    getParentRoute: () => SettingsroutesSettingsRoute,
  } as any)
const SettingsroutesSettingsGeneralRoute =
  SettingsroutesSettingsGeneralRouteImport.update({
    id: '/general',
    path: '/general',
    getParentRoute: () => SettingsroutesSettingsRoute,
  } as any)
const AuthroutesResetTokenIdRoute = AuthroutesResetTokenIdRouteImport.update({
  id: '/$tokenId',
  path: '/$tokenId',
  getParentRoute: () => AuthroutesResetRoute,
} as any)
const ApproutesOnboardingSubscriptionRoute =
  ApproutesOnboardingSubscriptionRouteImport.update({
    id: '/(routes)/onboarding/subscription',
    path: '/onboarding/subscription',
    getParentRoute: () => AppRouteRoute,
  } as any)
const ApproutesOnboardingSchoolRoute =
  ApproutesOnboardingSchoolRouteImport.update({
    id: '/(routes)/onboarding/school',
    path: '/onboarding/school',
    getParentRoute: () => AppRouteRoute,
  } as any)
const ApproutesOnboardingDancerRoute =
  ApproutesOnboardingDancerRouteImport.update({
    id: '/(routes)/onboarding/dancer',
    path: '/onboarding/dancer',
    getParentRoute: () => AppRouteRoute,
  } as any)
const ApproutesEventsEventIdRoute = ApproutesEventsEventIdRouteImport.update({
  id: '/$eventId',
  path: '/$eventId',
  getParentRoute: () => ApproutesEventsRoute,
} as any)
const AdminroutesDashboardMetricsRoute =
  AdminroutesDashboardMetricsRouteImport.update({
    id: '/metrics',
    path: '/metrics',
    getParentRoute: () => AdminroutesDashboardRoute,
  } as any)
const AdminroutesDashboardAssetsRoute =
  AdminroutesDashboardAssetsRouteImport.update({
    id: '/assets',
    path: '/assets',
    getParentRoute: () => AdminroutesDashboardRoute,
  } as any)
const ApproutesUUsernameIndexRoute = ApproutesUUsernameIndexRouteImport.update({
  id: '/(routes)/u/$username/',
  path: '/u/$username/',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApproutesSchoolUsernameIndexRoute =
  ApproutesSchoolUsernameIndexRouteImport.update({
    id: '/(routes)/school/$username/',
    path: '/school/$username/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const ApproutesUUsernameRecruitingRoute =
  ApproutesUUsernameRecruitingRouteImport.update({
    id: '/(routes)/u/$username/recruiting',
    path: '/u/$username/recruiting',
    getParentRoute: () => AppRouteRoute,
  } as any)
const ApproutesSchoolUsernameRecruitingRoute =
  ApproutesSchoolUsernameRecruitingRouteImport.update({
    id: '/(routes)/school/$username/recruiting',
    path: '/school/$username/recruiting',
    getParentRoute: () => AppRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ApproutesIndexRoute
  '/dashboard': typeof AdminroutesDashboardRouteWithChildren
  '/events': typeof ApproutesEventsRouteWithChildren
  '/explore': typeof ApproutesExploreRoute
  '/resources': typeof ApproutesResourcesRoute
  '/session': typeof ApproutesSessionRoute
  '/unauthorized': typeof ApproutesUnauthorizedRoute
  '/login': typeof AuthroutesLoginRoute
  '/reset': typeof AuthroutesResetRouteWithChildren
  '/signup': typeof AuthroutesSignupRoute
  '/settings': typeof SettingsroutesSettingsRouteWithChildren
  '/dashboard/assets': typeof AdminroutesDashboardAssetsRoute
  '/dashboard/metrics': typeof AdminroutesDashboardMetricsRoute
  '/events/$eventId': typeof ApproutesEventsEventIdRoute
  '/onboarding/dancer': typeof ApproutesOnboardingDancerRoute
  '/onboarding/school': typeof ApproutesOnboardingSchoolRoute
  '/onboarding/subscription': typeof ApproutesOnboardingSubscriptionRoute
  '/reset/$tokenId': typeof AuthroutesResetTokenIdRoute
  '/settings/general': typeof SettingsroutesSettingsGeneralRoute
  '/settings/media': typeof SettingsroutesSettingsMediaRoute
  '/settings/profile': typeof SettingsroutesSettingsProfileRoute
  '/school/$username/recruiting': typeof ApproutesSchoolUsernameRecruitingRoute
  '/u/$username/recruiting': typeof ApproutesUUsernameRecruitingRoute
  '/school/$username/': typeof ApproutesSchoolUsernameIndexRoute
  '/u/$username/': typeof ApproutesUUsernameIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof ApproutesIndexRoute
  '/dashboard': typeof AdminroutesDashboardRouteWithChildren
  '/events': typeof ApproutesEventsRouteWithChildren
  '/explore': typeof ApproutesExploreRoute
  '/resources': typeof ApproutesResourcesRoute
  '/session': typeof ApproutesSessionRoute
  '/unauthorized': typeof ApproutesUnauthorizedRoute
  '/login': typeof AuthroutesLoginRoute
  '/reset': typeof AuthroutesResetRouteWithChildren
  '/signup': typeof AuthroutesSignupRoute
  '/settings': typeof SettingsroutesSettingsRouteWithChildren
  '/dashboard/assets': typeof AdminroutesDashboardAssetsRoute
  '/dashboard/metrics': typeof AdminroutesDashboardMetricsRoute
  '/events/$eventId': typeof ApproutesEventsEventIdRoute
  '/onboarding/dancer': typeof ApproutesOnboardingDancerRoute
  '/onboarding/school': typeof ApproutesOnboardingSchoolRoute
  '/onboarding/subscription': typeof ApproutesOnboardingSubscriptionRoute
  '/reset/$tokenId': typeof AuthroutesResetTokenIdRoute
  '/settings/general': typeof SettingsroutesSettingsGeneralRoute
  '/settings/media': typeof SettingsroutesSettingsMediaRoute
  '/settings/profile': typeof SettingsroutesSettingsProfileRoute
  '/school/$username/recruiting': typeof ApproutesSchoolUsernameRecruitingRoute
  '/u/$username/recruiting': typeof ApproutesUUsernameRecruitingRoute
  '/school/$username': typeof ApproutesSchoolUsernameIndexRoute
  '/u/$username': typeof ApproutesUUsernameIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_admin': typeof AdminRouteRouteWithChildren
  '/_app': typeof AppRouteRouteWithChildren
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_settings': typeof SettingsRouteRouteWithChildren
  '/_admin/(routes)/dashboard': typeof AdminroutesDashboardRouteWithChildren
  '/_app/(routes)/events': typeof ApproutesEventsRouteWithChildren
  '/_app/(routes)/explore': typeof ApproutesExploreRoute
  '/_app/(routes)/resources': typeof ApproutesResourcesRoute
  '/_app/(routes)/session': typeof ApproutesSessionRoute
  '/_app/(routes)/unauthorized': typeof ApproutesUnauthorizedRoute
  '/_auth/(routes)/login': typeof AuthroutesLoginRoute
  '/_auth/(routes)/reset': typeof AuthroutesResetRouteWithChildren
  '/_auth/(routes)/signup': typeof AuthroutesSignupRoute
  '/_settings/(routes)/settings': typeof SettingsroutesSettingsRouteWithChildren
  '/_app/(routes)/': typeof ApproutesIndexRoute
  '/_admin/(routes)/dashboard/assets': typeof AdminroutesDashboardAssetsRoute
  '/_admin/(routes)/dashboard/metrics': typeof AdminroutesDashboardMetricsRoute
  '/_app/(routes)/events/$eventId': typeof ApproutesEventsEventIdRoute
  '/_app/(routes)/onboarding/dancer': typeof ApproutesOnboardingDancerRoute
  '/_app/(routes)/onboarding/school': typeof ApproutesOnboardingSchoolRoute
  '/_app/(routes)/onboarding/subscription': typeof ApproutesOnboardingSubscriptionRoute
  '/_auth/(routes)/reset/$tokenId': typeof AuthroutesResetTokenIdRoute
  '/_settings/(routes)/settings/general': typeof SettingsroutesSettingsGeneralRoute
  '/_settings/(routes)/settings/media': typeof SettingsroutesSettingsMediaRoute
  '/_settings/(routes)/settings/profile': typeof SettingsroutesSettingsProfileRoute
  '/_app/(routes)/school/$username/recruiting': typeof ApproutesSchoolUsernameRecruitingRoute
  '/_app/(routes)/u/$username/recruiting': typeof ApproutesUUsernameRecruitingRoute
  '/_app/(routes)/school/$username/': typeof ApproutesSchoolUsernameIndexRoute
  '/_app/(routes)/u/$username/': typeof ApproutesUUsernameIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/events'
    | '/explore'
    | '/resources'
    | '/session'
    | '/unauthorized'
    | '/login'
    | '/reset'
    | '/signup'
    | '/settings'
    | '/dashboard/assets'
    | '/dashboard/metrics'
    | '/events/$eventId'
    | '/onboarding/dancer'
    | '/onboarding/school'
    | '/onboarding/subscription'
    | '/reset/$tokenId'
    | '/settings/general'
    | '/settings/media'
    | '/settings/profile'
    | '/school/$username/recruiting'
    | '/u/$username/recruiting'
    | '/school/$username/'
    | '/u/$username/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/events'
    | '/explore'
    | '/resources'
    | '/session'
    | '/unauthorized'
    | '/login'
    | '/reset'
    | '/signup'
    | '/settings'
    | '/dashboard/assets'
    | '/dashboard/metrics'
    | '/events/$eventId'
    | '/onboarding/dancer'
    | '/onboarding/school'
    | '/onboarding/subscription'
    | '/reset/$tokenId'
    | '/settings/general'
    | '/settings/media'
    | '/settings/profile'
    | '/school/$username/recruiting'
    | '/u/$username/recruiting'
    | '/school/$username'
    | '/u/$username'
  id:
    | '__root__'
    | '/_admin'
    | '/_app'
    | '/_auth'
    | '/_settings'
    | '/_admin/(routes)/dashboard'
    | '/_app/(routes)/events'
    | '/_app/(routes)/explore'
    | '/_app/(routes)/resources'
    | '/_app/(routes)/session'
    | '/_app/(routes)/unauthorized'
    | '/_auth/(routes)/login'
    | '/_auth/(routes)/reset'
    | '/_auth/(routes)/signup'
    | '/_settings/(routes)/settings'
    | '/_app/(routes)/'
    | '/_admin/(routes)/dashboard/assets'
    | '/_admin/(routes)/dashboard/metrics'
    | '/_app/(routes)/events/$eventId'
    | '/_app/(routes)/onboarding/dancer'
    | '/_app/(routes)/onboarding/school'
    | '/_app/(routes)/onboarding/subscription'
    | '/_auth/(routes)/reset/$tokenId'
    | '/_settings/(routes)/settings/general'
    | '/_settings/(routes)/settings/media'
    | '/_settings/(routes)/settings/profile'
    | '/_app/(routes)/school/$username/recruiting'
    | '/_app/(routes)/u/$username/recruiting'
    | '/_app/(routes)/school/$username/'
    | '/_app/(routes)/u/$username/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  SettingsRouteRoute: typeof SettingsRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_settings': {
      id: '/_settings'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SettingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/(routes)/': {
      id: '/_app/(routes)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ApproutesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_settings/(routes)/settings': {
      id: '/_settings/(routes)/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsroutesSettingsRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/_auth/(routes)/signup': {
      id: '/_auth/(routes)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthroutesSignupRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/(routes)/reset': {
      id: '/_auth/(routes)/reset'
      path: '/reset'
      fullPath: '/reset'
      preLoaderRoute: typeof AuthroutesResetRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/(routes)/login': {
      id: '/_auth/(routes)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthroutesLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_app/(routes)/unauthorized': {
      id: '/_app/(routes)/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof ApproutesUnauthorizedRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/(routes)/session': {
      id: '/_app/(routes)/session'
      path: '/session'
      fullPath: '/session'
      preLoaderRoute: typeof ApproutesSessionRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/(routes)/resources': {
      id: '/_app/(routes)/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ApproutesResourcesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/(routes)/explore': {
      id: '/_app/(routes)/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ApproutesExploreRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/(routes)/events': {
      id: '/_app/(routes)/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof ApproutesEventsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_admin/(routes)/dashboard': {
      id: '/_admin/(routes)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AdminroutesDashboardRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_settings/(routes)/settings/profile': {
      id: '/_settings/(routes)/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsroutesSettingsProfileRouteImport
      parentRoute: typeof SettingsroutesSettingsRoute
    }
    '/_settings/(routes)/settings/media': {
      id: '/_settings/(routes)/settings/media'
      path: '/media'
      fullPath: '/settings/media'
      preLoaderRoute: typeof SettingsroutesSettingsMediaRouteImport
      parentRoute: typeof SettingsroutesSettingsRoute
    }
    '/_settings/(routes)/settings/general': {
      id: '/_settings/(routes)/settings/general'
      path: '/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof SettingsroutesSettingsGeneralRouteImport
      parentRoute: typeof SettingsroutesSettingsRoute
    }
    '/_auth/(routes)/reset/$tokenId': {
      id: '/_auth/(routes)/reset/$tokenId'
      path: '/$tokenId'
      fullPath: '/reset/$tokenId'
      preLoaderRoute: typeof AuthroutesResetTokenIdRouteImport
      parentRoute: typeof AuthroutesResetRoute
    }
    '/_app/(routes)/onboarding/subscription': {
      id: '/_app/(routes)/onboarding/subscription'
      path: '/onboarding/subscription'
      fullPath: '/onboarding/subscription'
      preLoaderRoute: typeof ApproutesOnboardingSubscriptionRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/(routes)/onboarding/school': {
      id: '/_app/(routes)/onboarding/school'
      path: '/onboarding/school'
      fullPath: '/onboarding/school'
      preLoaderRoute: typeof ApproutesOnboardingSchoolRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/(routes)/onboarding/dancer': {
      id: '/_app/(routes)/onboarding/dancer'
      path: '/onboarding/dancer'
      fullPath: '/onboarding/dancer'
      preLoaderRoute: typeof ApproutesOnboardingDancerRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/(routes)/events/$eventId': {
      id: '/_app/(routes)/events/$eventId'
      path: '/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof ApproutesEventsEventIdRouteImport
      parentRoute: typeof ApproutesEventsRoute
    }
    '/_admin/(routes)/dashboard/metrics': {
      id: '/_admin/(routes)/dashboard/metrics'
      path: '/metrics'
      fullPath: '/dashboard/metrics'
      preLoaderRoute: typeof AdminroutesDashboardMetricsRouteImport
      parentRoute: typeof AdminroutesDashboardRoute
    }
    '/_admin/(routes)/dashboard/assets': {
      id: '/_admin/(routes)/dashboard/assets'
      path: '/assets'
      fullPath: '/dashboard/assets'
      preLoaderRoute: typeof AdminroutesDashboardAssetsRouteImport
      parentRoute: typeof AdminroutesDashboardRoute
    }
    '/_app/(routes)/u/$username/': {
      id: '/_app/(routes)/u/$username/'
      path: '/u/$username'
      fullPath: '/u/$username/'
      preLoaderRoute: typeof ApproutesUUsernameIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/(routes)/school/$username/': {
      id: '/_app/(routes)/school/$username/'
      path: '/school/$username'
      fullPath: '/school/$username/'
      preLoaderRoute: typeof ApproutesSchoolUsernameIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/(routes)/u/$username/recruiting': {
      id: '/_app/(routes)/u/$username/recruiting'
      path: '/u/$username/recruiting'
      fullPath: '/u/$username/recruiting'
      preLoaderRoute: typeof ApproutesUUsernameRecruitingRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/(routes)/school/$username/recruiting': {
      id: '/_app/(routes)/school/$username/recruiting'
      path: '/school/$username/recruiting'
      fullPath: '/school/$username/recruiting'
      preLoaderRoute: typeof ApproutesSchoolUsernameRecruitingRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AdminroutesDashboardRouteChildren {
  AdminroutesDashboardAssetsRoute: typeof AdminroutesDashboardAssetsRoute
  AdminroutesDashboardMetricsRoute: typeof AdminroutesDashboardMetricsRoute
}

const AdminroutesDashboardRouteChildren: AdminroutesDashboardRouteChildren = {
  AdminroutesDashboardAssetsRoute: AdminroutesDashboardAssetsRoute,
  AdminroutesDashboardMetricsRoute: AdminroutesDashboardMetricsRoute,
}

const AdminroutesDashboardRouteWithChildren =
  AdminroutesDashboardRoute._addFileChildren(AdminroutesDashboardRouteChildren)

interface AdminRouteRouteChildren {
  AdminroutesDashboardRoute: typeof AdminroutesDashboardRouteWithChildren
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminroutesDashboardRoute: AdminroutesDashboardRouteWithChildren,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface ApproutesEventsRouteChildren {
  ApproutesEventsEventIdRoute: typeof ApproutesEventsEventIdRoute
}

const ApproutesEventsRouteChildren: ApproutesEventsRouteChildren = {
  ApproutesEventsEventIdRoute: ApproutesEventsEventIdRoute,
}

const ApproutesEventsRouteWithChildren = ApproutesEventsRoute._addFileChildren(
  ApproutesEventsRouteChildren,
)

interface AppRouteRouteChildren {
  ApproutesEventsRoute: typeof ApproutesEventsRouteWithChildren
  ApproutesExploreRoute: typeof ApproutesExploreRoute
  ApproutesResourcesRoute: typeof ApproutesResourcesRoute
  ApproutesSessionRoute: typeof ApproutesSessionRoute
  ApproutesUnauthorizedRoute: typeof ApproutesUnauthorizedRoute
  ApproutesIndexRoute: typeof ApproutesIndexRoute
  ApproutesOnboardingDancerRoute: typeof ApproutesOnboardingDancerRoute
  ApproutesOnboardingSchoolRoute: typeof ApproutesOnboardingSchoolRoute
  ApproutesOnboardingSubscriptionRoute: typeof ApproutesOnboardingSubscriptionRoute
  ApproutesSchoolUsernameRecruitingRoute: typeof ApproutesSchoolUsernameRecruitingRoute
  ApproutesUUsernameRecruitingRoute: typeof ApproutesUUsernameRecruitingRoute
  ApproutesSchoolUsernameIndexRoute: typeof ApproutesSchoolUsernameIndexRoute
  ApproutesUUsernameIndexRoute: typeof ApproutesUUsernameIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  ApproutesEventsRoute: ApproutesEventsRouteWithChildren,
  ApproutesExploreRoute: ApproutesExploreRoute,
  ApproutesResourcesRoute: ApproutesResourcesRoute,
  ApproutesSessionRoute: ApproutesSessionRoute,
  ApproutesUnauthorizedRoute: ApproutesUnauthorizedRoute,
  ApproutesIndexRoute: ApproutesIndexRoute,
  ApproutesOnboardingDancerRoute: ApproutesOnboardingDancerRoute,
  ApproutesOnboardingSchoolRoute: ApproutesOnboardingSchoolRoute,
  ApproutesOnboardingSubscriptionRoute: ApproutesOnboardingSubscriptionRoute,
  ApproutesSchoolUsernameRecruitingRoute:
    ApproutesSchoolUsernameRecruitingRoute,
  ApproutesUUsernameRecruitingRoute: ApproutesUUsernameRecruitingRoute,
  ApproutesSchoolUsernameIndexRoute: ApproutesSchoolUsernameIndexRoute,
  ApproutesUUsernameIndexRoute: ApproutesUUsernameIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface AuthroutesResetRouteChildren {
  AuthroutesResetTokenIdRoute: typeof AuthroutesResetTokenIdRoute
}

const AuthroutesResetRouteChildren: AuthroutesResetRouteChildren = {
  AuthroutesResetTokenIdRoute: AuthroutesResetTokenIdRoute,
}

const AuthroutesResetRouteWithChildren = AuthroutesResetRoute._addFileChildren(
  AuthroutesResetRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthroutesLoginRoute: typeof AuthroutesLoginRoute
  AuthroutesResetRoute: typeof AuthroutesResetRouteWithChildren
  AuthroutesSignupRoute: typeof AuthroutesSignupRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthroutesLoginRoute: AuthroutesLoginRoute,
  AuthroutesResetRoute: AuthroutesResetRouteWithChildren,
  AuthroutesSignupRoute: AuthroutesSignupRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface SettingsroutesSettingsRouteChildren {
  SettingsroutesSettingsGeneralRoute: typeof SettingsroutesSettingsGeneralRoute
  SettingsroutesSettingsMediaRoute: typeof SettingsroutesSettingsMediaRoute
  SettingsroutesSettingsProfileRoute: typeof SettingsroutesSettingsProfileRoute
}

const SettingsroutesSettingsRouteChildren: SettingsroutesSettingsRouteChildren =
  {
    SettingsroutesSettingsGeneralRoute: SettingsroutesSettingsGeneralRoute,
    SettingsroutesSettingsMediaRoute: SettingsroutesSettingsMediaRoute,
    SettingsroutesSettingsProfileRoute: SettingsroutesSettingsProfileRoute,
  }

const SettingsroutesSettingsRouteWithChildren =
  SettingsroutesSettingsRoute._addFileChildren(
    SettingsroutesSettingsRouteChildren,
  )

interface SettingsRouteRouteChildren {
  SettingsroutesSettingsRoute: typeof SettingsroutesSettingsRouteWithChildren
}

const SettingsRouteRouteChildren: SettingsRouteRouteChildren = {
  SettingsroutesSettingsRoute: SettingsroutesSettingsRouteWithChildren,
}

const SettingsRouteRouteWithChildren = SettingsRouteRoute._addFileChildren(
  SettingsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  SettingsRouteRoute: SettingsRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
