export const filters = [
  {
    label: "School Name",
    id: "school-name",
    type: "input",
    paramKey: "name",
  },
  {
    label: "Common Recruiting Application",
    id: "common-recruiting-application",
    type: "toggle",
    paramKey: "commonRecruitingApplication",
  },
  {
    label: "Division",
    id: "division",
    type: "select",
    paramKey: "division",
    options: [
      { label: "None", value: "None" },
      { label: "Division IA", value: "Division IA" },
      { label: "Division I", value: "Division I" },
      { label: "Division II", value: "Division II" },
      { label: "Division III", value: "Division III" },
      { label: "NAIA", value: "NAIA" },
    ],
  },
  {
    label: "GPA Range",
    id: "gpa-range",
    type: "select",
    paramKey: "gpaRange",
    options: [
      { value: "4", label: "4+" },
      { value: "3.75", label: "3.75+" },
      { value: "3.5", label: "3.5+" },
      { value: "3.25", label: "3.25+" },
      { value: "3.0", label: "3.0+" },
      { value: "2.75", label: "2.75+" },
      { value: "2.5", label: "2.5+" },
      { value: "2.25", label: "2.25+" },
      { value: "0", label: "None" },
    ],
  },
  {
    label: "Location",
    id: "location",
    type: "select",
    paramKey: "location",
    options: [
      { label: "None", value: "None" },
      { label: "Alabama", value: "Alabama" },
      { label: "Alaska", value: "Alaska" },
      { label: "Arizona", value: "Arizona" },
      { label: "Arkansas", value: "Arkansas" },
      { label: "California", value: "California" },
      { label: "Colorado", value: "Colorado" },
      { label: "Connecticut", value: "Connecticut" },
      { label: "Delaware", value: "Delaware" },
      { label: "Florida", value: "Florida" },
      { label: "Georgia", value: "Georgia" },
      { label: "Hawaii", value: "Hawaii" },
      { label: "Idaho", value: "Idaho" },
      { label: "Illinois", value: "Illinois" },
      { label: "Indiana", value: "Indiana" },
      { label: "Iowa", value: "Iowa" },
      { label: "Kansas", value: "Kansas" },
      { label: "Kentucky", value: "Kentucky" },
      { label: "Louisiana", value: "Louisiana" },
      { label: "Maine", value: "Maine" },
      { label: "Maryland", value: "Maryland" },
      { label: "Massachusetts", value: "Massachusetts" },
      { label: "Michigan", value: "Michigan" },
      { label: "Minnesota", value: "Minnesota" },
      { label: "Mississippi", value: "Mississippi" },
      { label: "Missouri", value: "Missouri" },
      { label: "Montana", value: "Montana" },
      { label: "Nebraska", value: "Nebraska" },
      { label: "Nevada", value: "Nevada" },
      { label: "New Hampshire", value: "New Hampshire" },
      { label: "New Jersey", value: "New Jersey" },
      { label: "New Mexico", value: "New Mexico" },
      { label: "New York", value: "New York" },
      { label: "North Carolina", value: "North Carolina" },
      { label: "North Dakota", value: "North Dakota" },
      { label: "Ohio", value: "Ohio" },
      { label: "Oklahoma", value: "Oklahoma" },
      { label: "Oregon", value: "Oregon" },
      { label: "Pennsylvania", value: "Pennsylvania" },
      { label: "Rhode Island", value: "Rhode Island" },
      { label: "South Carolina", value: "South Carolina" },
      { label: "South Dakota", value: "South Dakota" },
      { label: "Tennessee", value: "Tennessee" },
      { label: "Texas", value: "Texas" },
      { label: "Utah", value: "Utah" },
      { label: "Vermont", value: "Vermont" },
      { label: "Virginia", value: "Virginia" },
      { label: "Washington", value: "Washington" },
      { label: "West Virginia", value: "West Virginia" },
      { label: "Wisconsin", value: "Wisconsin" },
      { label: "Wyoming", value: "Wyoming" },
    ],
  },
  {
    label: "Sports",
    id: "sports",
    type: "select",
    paramKey: "sports",
    options: [
      { label: "None", value: "None" },
      { label: "Football", value: "Football" },
      { label: "Basketball", value: "Basketball" },
      { label: "Volleyball", value: "Volleyball" },
      { label: "Soccer", value: "Soccer" },
      { label: "Baseball", value: "Baseball" },
      { label: "Gymnastics", value: "Gymnastics" },
      { label: "Swim", value: "Swim" },
      { label: "Tennis", value: "Tennis" },
      { label: "Hockey", value: "Hockey" },
      { label: "Lacrosse", value: "Lacrosse" },
      { label: "Golf", value: "Golf" },
      { label: "Skiing", value: "Skiing" },
      { label: "Wrestling", value: "Wrestling" },
      { label: "Water Polo", value: "Water Polo" },
      { label: "Track and Field", value: "Track and Field" },
      { label: "Softball", value: "Softball" },
      { label: "Rowing", value: "Rowing" },
      { label: "Other", value: "Other" },
    ],
  },
  {
    label: "Styles",
    id: "styles",
    type: "select",
    paramKey: "styles",
    options: [
      { value: "Hip Hop", label: "Hip Hop" },
      { value: "Jazz", label: "Jazz" },
      { value: "Pom", label: "Pom" },
      { value: "Game Day", label: "Game Day" },
      { value: "Kick", label: "Kick" },
      { value: "Military", label: "Military" },
      { value: "Lyrical/Comtemporary", label: "Lyrical/Comtemporary" },
      { value: "Team Performance", label: "Team Performance" },
      { value: "Non-competitive", label: "Non-competitive" },
    ],
  },
  {
    label: "Upcoming Events",
    id: "upcoming-events",
    type: "toggle",
    paramKey: "hasUpcomingEvents",
  },
  {
    label: "Team Selection",
    id: "team-selection",
    type: "input",
    paramKey: "teamSelection",
  },
  {
    label: "Team Type",
    id: "team-type",
    type: "input",
    paramKey: "teamType",
  },
];
