// @ts-nocheck
/* eslint-disable */
// --------------------------------------------------
// This file is auto-generated by Tuyau. Do not edit manually !
// --------------------------------------------------

import type { MakeTuyauRequest, MakeTuyauResponse } from '@tuyau/utils/types'
import type { InferInput } from '@vinejs/vine/types'

type ApplicationGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/modules/applications/get-application/controller.ts').default['handle'], false>
}
type ApplicationPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/modules/applications/submit-application/validator.ts')['validator']>>
  response: MakeTuyauResponse<import('../app/modules/applications/submit-application/controller.ts').default['handle'], true>
}
type ApplicationPatch = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/modules/applications/update-application/validator.ts')['validator']>>
  response: MakeTuyauResponse<import('../app/modules/applications/update-application/controller.ts').default['handle'], true>
}
type AuthSignupPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/modules/auth/signup/validator.ts')['validator']>>
  response: MakeTuyauResponse<import('../app/modules/auth/signup/controller.ts').default['handle'], true>
}
type AuthLoginPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/modules/auth/login/validator.ts')['validator']>>
  response: MakeTuyauResponse<import('../app/modules/auth/login/controller.ts').default['handle'], true>
}
type AuthLogoutPost = {
  request: unknown
  response: MakeTuyauResponse<import('../app/modules/auth/logout/controller.ts').default['handle'], false>
}
type AuthSessionGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/modules/auth/get-session/controller.ts').default['handle'], false>
}
type AuthPasswordChangePost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/modules/auth/change-password/validator.ts')['schema']>>
  response: MakeTuyauResponse<import('../app/modules/auth/change-password/controller.ts').default['handle'], true>
}
type AuthPasswordResetPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/modules/auth/change-password/validator.ts')['schema']>>
  response: MakeTuyauResponse<import('../app/modules/auth/change-password/controller.ts').default['handle'], true>
}
type BlogGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/modules/blog/get-posts/controller.ts').default['handle'], false>
}
type FeedGetHead = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/modules/feed/get-feed/validator.ts')['validator']>>
  response: MakeTuyauResponse<import('../app/modules/feed/get-feed/controller.ts').default['handle'], true>
}
type HealthGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/modules/health/index.ts').default['handle'], false>
}
type LibraryGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/modules/library/list-videos/controller.ts').default['handle'], false>
}
type LibraryIdGetHead = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/modules/library/list-videos-by-category/validator.ts')['validator']>>
  response: MakeTuyauResponse<import('../app/modules/library/list-videos-by-category/controller.ts').default['handle'], true>
}
type SkillsGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/modules/skills/get-skills/controller.ts').default['handle'], false>
}
type SportsGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/modules/sports/get-sports/controller.ts').default['handle'], false>
}
type StylesGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/modules/styles/get-styles/controller.ts').default['handle'], false>
}
type SubscriptionsStatusGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/modules/subscriptions/status/controller.ts').default['handle'], false>
}
type SubscriptionsCheckoutPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/modules/subscriptions/checkout/validator.ts')['schema']>>
  response: MakeTuyauResponse<import('../app/modules/subscriptions/checkout/controller.ts').default['handle'], true>
}
type SubscriptionsManagePost = {
  request: unknown
  response: MakeTuyauResponse<import('../app/modules/subscriptions/manage/controller.ts').default['handle'], false>
}
type StripeWebhookPost = {
  request: unknown
  response: MakeTuyauResponse<import('../app/modules/webhooks/stripe/controller.ts').default['handle'], false>
}
type DancersPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/modules/dancers/profile/create-dancer/validator.ts')['validator']>>
  response: MakeTuyauResponse<import('../app/modules/dancers/profile/create-dancer/controller.ts').default['handle'], true>
}
type DancersFiltersGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/modules/dancers/explore/get-dancer-filters/controller.ts').default['handle'], false>
}
type DancersGetHead = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/modules/dancers/explore/get-dancers/validator.ts')['validator']>>
  response: MakeTuyauResponse<import('../app/modules/dancers/explore/get-dancers/controller.ts').default['handle'], true>
}
type DancersMeSkillsGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/modules/dancers/profile/get-skills/controller.ts').default['handle'], false>
}
type DancersMeSkillsPatch = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/modules/dancers/profile/update-skills/validator.ts')['schema']>>
  response: MakeTuyauResponse<import('../app/modules/dancers/profile/update-skills/controller.ts').default['handle'], true>
}
type DancersMeStylesGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/modules/dancers/profile/get-styles/controller.ts').default['handle'], false>
}
type DancersMeStylesPatch = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/modules/dancers/profile/update-styles/validator.ts')['schema']>>
  response: MakeTuyauResponse<import('../app/modules/dancers/profile/update-styles/controller.ts').default['handle'], true>
}
type DancersMeSportsGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/modules/dancers/profile/get-sports/controller.ts').default['handle'], false>
}
type DancersMeSportsPatch = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/modules/dancers/profile/update-sports/validator.ts')['schema']>>
  response: MakeTuyauResponse<import('../app/modules/dancers/profile/update-sports/controller.ts').default['handle'], true>
}
type DancersMeFollowingGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/modules/dancers/engagement/get-following/controller.ts').default['handle'], false>
}
type DancersMeFollowingIdsGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/modules/dancers/engagement/get-following-ids/controller.ts').default['handle'], false>
}
type DancersMePortfolioPatch = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/modules/dancers/profile/update-portfolio/validator.ts')['validator']>>
  response: MakeTuyauResponse<import('../app/modules/dancers/profile/update-portfolio/controller.ts').default['handle'], true>
}
type DancersMeFollowersGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/modules/dancers/engagement/get-followers/controller.ts').default['handle'], false>
}
type DancersMeChecklistGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/modules/dancers/profile/get-profile-checklist/controller.ts').default['handle'], false>
}
type DancersMeReferencesPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/modules/dancers/profile/create-reference/validator.ts')['schema']>>
  response: MakeTuyauResponse<import('../app/modules/dancers/profile/create-reference/controller.ts').default['handle'], true>
}
type DancersMeReferencesIdDelete = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/modules/dancers/profile/delete-reference/validator.ts')['schema']>>
  response: MakeTuyauResponse<import('../app/modules/dancers/profile/delete-reference/controller.ts').default['handle'], true>
}
type DancersMeAchievementsPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/modules/dancers/profile/create-achievement/validator.ts')['schema']>>
  response: MakeTuyauResponse<import('../app/modules/dancers/profile/create-achievement/controller.ts').default['handle'], true>
}
type DancersMeAchievementsIdDelete = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/modules/dancers/profile/delete-achievement/validator.ts')['schema']>>
  response: MakeTuyauResponse<import('../app/modules/dancers/profile/delete-achievement/controller.ts').default['handle'], true>
}
type DancersSubmissionsGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/modules/dancers/common-recruiting/get-submissions/controller.ts').default['handle'], false>
}
type DancersSubmissionsPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/modules/dancers/common-recruiting/create-submission/validator.ts')['schema']>>
  response: MakeTuyauResponse<import('../app/modules/dancers/common-recruiting/create-submission/controller.ts').default['handle'], true>
}
type DancersSubmissionsSchoolsGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/modules/dancers/common-recruiting/get-submission-schools/controller.ts').default['handle'], false>
}
type DancersSubmissionsVideoGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/modules/dancers/common-recruiting/get-submission-video/controller.ts').default['handle'], false>
}
type DancersIdGetHead = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/modules/dancers/profile/get-dancer/validator.ts')['validator']>>
  response: MakeTuyauResponse<import('../app/modules/dancers/profile/get-dancer/controller.ts').default['handle'], true>
}
type DancersIdFavoritePost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/modules/dancers/engagement/favorite/validator.ts')['schema']>>
  response: MakeTuyauResponse<import('../app/modules/dancers/engagement/favorite/controller.ts').default['handle'], true>
}
type DancersIdFavoriteDelete = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/modules/dancers/engagement/unfavorite/validator.ts')['schema']>>
  response: MakeTuyauResponse<import('../app/modules/dancers/engagement/unfavorite/controller.ts').default['handle'], true>
}
type DancersIdMetadataGetHead = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/modules/dancers/profile/get-dancer-metadata/validator.ts')['schema']>>
  response: MakeTuyauResponse<import('../app/modules/dancers/profile/get-dancer-metadata/controller.ts').default['handle'], true>
}
type EventsGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/modules/events/get-events/controller.ts').default['handle'], false>
}
type EventsUpcomingGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/modules/events/get-upcoming-events/controller.ts').default['handle'], false>
}
type EventsGlobalGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/modules/events/get-global-events/controller.ts').default['handle'], false>
}
type EventsIdGetHead = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/modules/events/get-event-by-id/validator.ts')['validator']>>
  response: MakeTuyauResponse<import('../app/modules/events/get-event-by-id/controller.ts').default['handle'], true>
}
type EventsIdSavePost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/modules/events/save-event/validator.ts')['schema']>>
  response: MakeTuyauResponse<import('../app/modules/events/save-event/controller.ts').default['handle'], true>
}
type EventsIdUnsaveDelete = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/modules/events/unsave-event/validator.ts')['schema']>>
  response: MakeTuyauResponse<import('../app/modules/events/unsave-event/controller.ts').default['handle'], true>
}
type SchoolsFiltersGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/modules/schools/get-school-filters/controller.ts').default['handle'], false>
}
type SchoolsGetHead = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/modules/schools/get-schools/validator.ts')['validator']>>
  response: MakeTuyauResponse<import('../app/modules/schools/get-schools/controller.ts').default['handle'], true>
}
type SchoolsRecommendedGetHead = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/modules/schools/get-recommended-programs/validator.ts')['schema']>>
  response: MakeTuyauResponse<import('../app/modules/schools/get-recommended-programs/controller.ts').default['handle'], true>
}
type SchoolsMeFollowersGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/modules/schools/get-followers/controller.ts').default['handle'], false>
}
type SchoolsMeFollowingIdsGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/modules/schools/get-following-ids/controller.ts').default['handle'], false>
}
type SchoolsMeFollowingGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/modules/schools/get-following/controller.ts').default['handle'], false>
}
type SchoolsMeFavoritesGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/modules/schools/get-favorites-data/controller.ts').default['handle'], false>
}
type SchoolsMeFavoritesIdPatch = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/modules/schools/update-favorite/validator.ts')['schema']>>
  response: MakeTuyauResponse<import('../app/modules/schools/update-favorite/controller.ts').default['handle'], true>
}
type SchoolsIdGetHead = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/modules/schools/get-school/validator.ts')['validator']>>
  response: MakeTuyauResponse<import('../app/modules/schools/get-school/controller.ts').default['handle'], true>
}
type SchoolsIdFollowPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/modules/schools/follow/validator.ts')['schema']>>
  response: MakeTuyauResponse<import('../app/modules/schools/follow/controller.ts').default['handle'], true>
}
type SchoolsIdFollowDelete = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/modules/schools/unfollow/validator.ts')['schema']>>
  response: MakeTuyauResponse<import('../app/modules/schools/unfollow/controller.ts').default['handle'], true>
}
type SchoolsIdMetadataGetHead = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/modules/schools/get-school-metadata/validator.ts')['schema']>>
  response: MakeTuyauResponse<import('../app/modules/schools/get-school-metadata/controller.ts').default['handle'], true>
}
type SchoolsIdInterestPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/modules/schools/show-interest/validator.ts')['schema']>>
  response: MakeTuyauResponse<import('../app/modules/schools/show-interest/controller.ts').default['handle'], true>
}
type UsersCheckavailabilityGetHead = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/modules/users/check-availability/validator.ts')['validator']>>
  response: MakeTuyauResponse<import('../app/modules/users/check-availability/controller.ts').default['handle'], true>
}
type UsersAccountGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/modules/users/get-account/controller.ts').default['handle'], false>
}
type UsersAccountPatch = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/modules/users/update-account/validator.ts')['schema']>>
  response: MakeTuyauResponse<import('../app/modules/users/update-account/controller.ts').default['handle'], true>
}
type UsersAccountDelete = {
  request: unknown
  response: MakeTuyauResponse<import('../app/modules/users/delete-account/controller.ts').default['handle'], false>
}
type UsersActivityGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/modules/users/get-activity/controller.ts').default['handle'], false>
}
export interface ApiDefinition {
  'application': {
    '$url': {
    };
    '$get': ApplicationGetHead;
    '$head': ApplicationGetHead;
    '$post': ApplicationPost;
    '$patch': ApplicationPatch;
  };
  'auth': {
    'signup': {
      '$url': {
      };
      '$post': AuthSignupPost;
    };
    'login': {
      '$url': {
      };
      '$post': AuthLoginPost;
    };
    'logout': {
      '$url': {
      };
      '$post': AuthLogoutPost;
    };
    'session': {
      '$url': {
      };
      '$get': AuthSessionGetHead;
      '$head': AuthSessionGetHead;
    };
    'password': {
      'change': {
        '$url': {
        };
        '$post': AuthPasswordChangePost;
      };
      'reset': {
        '$url': {
        };
        '$post': AuthPasswordResetPost;
      };
    };
  };
  'blog': {
    '$url': {
    };
    '$get': BlogGetHead;
    '$head': BlogGetHead;
  };
  'feed': {
    '$url': {
    };
    '$get': FeedGetHead;
    '$head': FeedGetHead;
  };
  'health': {
    '$url': {
    };
    '$get': HealthGetHead;
    '$head': HealthGetHead;
  };
  'library': {
    '$url': {
    };
    '$get': LibraryGetHead;
    '$head': LibraryGetHead;
    ':category': {
      '$url': {
      };
      '$get': LibraryIdGetHead;
      '$head': LibraryIdGetHead;
    };
  };
  'skills': {
    '$url': {
    };
    '$get': SkillsGetHead;
    '$head': SkillsGetHead;
  };
  'sports': {
    '$url': {
    };
    '$get': SportsGetHead;
    '$head': SportsGetHead;
  };
  'styles': {
    '$url': {
    };
    '$get': StylesGetHead;
    '$head': StylesGetHead;
  };
  'subscriptions': {
    'status': {
      '$url': {
      };
      '$get': SubscriptionsStatusGetHead;
      '$head': SubscriptionsStatusGetHead;
    };
    'checkout': {
      '$url': {
      };
      '$post': SubscriptionsCheckoutPost;
    };
    'manage': {
      '$url': {
      };
      '$post': SubscriptionsManagePost;
    };
  };
  'stripe': {
    'webhook': {
      '$url': {
      };
      '$post': StripeWebhookPost;
    };
  };
  'dancers': {
    '$url': {
    };
    '$post': DancersPost;
    'filters': {
      '$url': {
      };
      '$get': DancersFiltersGetHead;
      '$head': DancersFiltersGetHead;
    };
    '$get': DancersGetHead;
    '$head': DancersGetHead;
    'me': {
      'skills': {
        '$url': {
        };
        '$get': DancersMeSkillsGetHead;
        '$head': DancersMeSkillsGetHead;
        '$patch': DancersMeSkillsPatch;
      };
      'styles': {
        '$url': {
        };
        '$get': DancersMeStylesGetHead;
        '$head': DancersMeStylesGetHead;
        '$patch': DancersMeStylesPatch;
      };
      'sports': {
        '$url': {
        };
        '$get': DancersMeSportsGetHead;
        '$head': DancersMeSportsGetHead;
        '$patch': DancersMeSportsPatch;
      };
      'following': {
        '$url': {
        };
        '$get': DancersMeFollowingGetHead;
        '$head': DancersMeFollowingGetHead;
        'ids': {
          '$url': {
          };
          '$get': DancersMeFollowingIdsGetHead;
          '$head': DancersMeFollowingIdsGetHead;
        };
      };
      'portfolio': {
        '$url': {
        };
        '$patch': DancersMePortfolioPatch;
      };
      'followers': {
        '$url': {
        };
        '$get': DancersMeFollowersGetHead;
        '$head': DancersMeFollowersGetHead;
      };
      'checklist': {
        '$url': {
        };
        '$get': DancersMeChecklistGetHead;
        '$head': DancersMeChecklistGetHead;
      };
      'references': {
        '$url': {
        };
        '$post': DancersMeReferencesPost;
        ':id': {
          '$url': {
          };
          '$delete': DancersMeReferencesIdDelete;
        };
      };
      'achievements': {
        '$url': {
        };
        '$post': DancersMeAchievementsPost;
        ':id': {
          '$url': {
          };
          '$delete': DancersMeAchievementsIdDelete;
        };
      };
    };
    'submissions': {
      '$url': {
      };
      '$get': DancersSubmissionsGetHead;
      '$head': DancersSubmissionsGetHead;
      '$post': DancersSubmissionsPost;
      'schools': {
        '$url': {
        };
        '$get': DancersSubmissionsSchoolsGetHead;
        '$head': DancersSubmissionsSchoolsGetHead;
      };
      'video': {
        '$url': {
        };
        '$get': DancersSubmissionsVideoGetHead;
        '$head': DancersSubmissionsVideoGetHead;
      };
    };
    ':username': {
      '$url': {
      };
      '$get': DancersIdGetHead;
      '$head': DancersIdGetHead;
    };
    ':id': {
      'favorite': {
        '$url': {
        };
        '$post': DancersIdFavoritePost;
        '$delete': DancersIdFavoriteDelete;
      };
      'metadata': {
        '$url': {
        };
        '$get': DancersIdMetadataGetHead;
        '$head': DancersIdMetadataGetHead;
      };
    };
  };
  'events': {
    '$url': {
    };
    '$get': EventsGetHead;
    '$head': EventsGetHead;
    'upcoming': {
      '$url': {
      };
      '$get': EventsUpcomingGetHead;
      '$head': EventsUpcomingGetHead;
    };
    'global': {
      '$url': {
      };
      '$get': EventsGlobalGetHead;
      '$head': EventsGlobalGetHead;
    };
    ':id': {
      '$url': {
      };
      '$get': EventsIdGetHead;
      '$head': EventsIdGetHead;
      'save': {
        '$url': {
        };
        '$post': EventsIdSavePost;
      };
      'unsave': {
        '$url': {
        };
        '$delete': EventsIdUnsaveDelete;
      };
    };
  };
  'schools': {
    'filters': {
      '$url': {
      };
      '$get': SchoolsFiltersGetHead;
      '$head': SchoolsFiltersGetHead;
    };
    '$url': {
    };
    '$get': SchoolsGetHead;
    '$head': SchoolsGetHead;
    'recommended': {
      '$url': {
      };
      '$get': SchoolsRecommendedGetHead;
      '$head': SchoolsRecommendedGetHead;
    };
    'me': {
      'followers': {
        '$url': {
        };
        '$get': SchoolsMeFollowersGetHead;
        '$head': SchoolsMeFollowersGetHead;
      };
      'following': {
        'ids': {
          '$url': {
          };
          '$get': SchoolsMeFollowingIdsGetHead;
          '$head': SchoolsMeFollowingIdsGetHead;
        };
        '$url': {
        };
        '$get': SchoolsMeFollowingGetHead;
        '$head': SchoolsMeFollowingGetHead;
      };
      'favorites': {
        '$url': {
        };
        '$get': SchoolsMeFavoritesGetHead;
        '$head': SchoolsMeFavoritesGetHead;
        ':id': {
          '$url': {
          };
          '$patch': SchoolsMeFavoritesIdPatch;
        };
      };
    };
    ':username': {
      '$url': {
      };
      '$get': SchoolsIdGetHead;
      '$head': SchoolsIdGetHead;
    };
    ':id': {
      'follow': {
        '$url': {
        };
        '$post': SchoolsIdFollowPost;
        '$delete': SchoolsIdFollowDelete;
      };
      'metadata': {
        '$url': {
        };
        '$get': SchoolsIdMetadataGetHead;
        '$head': SchoolsIdMetadataGetHead;
      };
      'interest': {
        '$url': {
        };
        '$post': SchoolsIdInterestPost;
      };
    };
  };
  'users': {
    'check-availability': {
      '$url': {
      };
      '$get': UsersCheckavailabilityGetHead;
      '$head': UsersCheckavailabilityGetHead;
    };
    'account': {
      '$url': {
      };
      '$get': UsersAccountGetHead;
      '$head': UsersAccountGetHead;
      '$patch': UsersAccountPatch;
      '$delete': UsersAccountDelete;
    };
    'activity': {
      '$url': {
      };
      '$get': UsersActivityGetHead;
      '$head': UsersActivityGetHead;
    };
  };
}
const routes = [
] as const;
export const api = {
  routes,
  definition: {} as ApiDefinition
}
