// @ts-nocheck
/* eslint-disable */
// --------------------------------------------------
// This file is auto-generated by Tuyau. Do not edit manually !
// --------------------------------------------------

import type { MakeTuyauRequest, MakeTuyauResponse } from '@tuyau/utils/types'
import type { InferInput } from '@vinejs/vine/types'

type AdminSchoolsIdApprovePost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/modules/admin/approve-school/validator.ts')['schema']>>
  response: MakeTuyauResponse<import('../app/modules/admin/approve-school/controller.ts').default['handle'], true>
}
type ApplicationGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/modules/applications/get-application/controller.ts').default['handle'], false>
}
type ApplicationPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/modules/applications/submit-application/schema.ts')['submitApplicationSchema']>>
  response: MakeTuyauResponse<import('../app/modules/applications/submit-application/controller.ts').default['handle'], true>
}
type ApplicationPatch = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/modules/applications/update-application/validator.ts')['updateApplicationSchema']>>
  response: MakeTuyauResponse<import('../app/modules/applications/update-application/controller.ts').default['handle'], true>
}
type AuthSignupPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/modules/auth/signup/validator.ts')['validator']>>
  response: MakeTuyauResponse<import('../app/modules/auth/signup/controller.ts').default['handle'], true>
}
type AuthLoginPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/modules/auth/login/validator.ts')['validator']>>
  response: MakeTuyauResponse<import('../app/modules/auth/login/controller.ts').default['handle'], true>
}
type AuthLogoutPost = {
  request: unknown
  response: MakeTuyauResponse<import('../app/modules/auth/logout/controller.ts').default['handle'], false>
}
type AuthSessionGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/modules/auth/get-session/controller.ts').default['handle'], false>
}
type AuthPasswordChangePost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/modules/auth/change-password/validator.ts')['schema']>>
  response: MakeTuyauResponse<import('../app/modules/auth/change-password/controller.ts').default['handle'], true>
}
type AuthPasswordForgotPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/modules/auth/forgot-password/schema.ts')['forgotPasswordSchema']>>
  response: MakeTuyauResponse<import('../app/modules/auth/forgot-password/controller.ts').default['handle'], true>
}
type AuthPasswordResetPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/modules/auth/reset-password/validator.ts')['schema']>>
  response: MakeTuyauResponse<import('../app/modules/auth/reset-password/controller.ts').default['handle'], true>
}
type BlogGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/modules/blog/get-posts/controller.ts').default['handle'], false>
}
type FeedGetHead = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/modules/feed/get-feed/validator.ts')['validator']>>
  response: MakeTuyauResponse<import('../app/modules/feed/get-feed/controller.ts').default['handle'], true>
}
type HealthGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/modules/health/index.ts').default['handle'], false>
}
type LibraryGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/modules/library/list-videos/controller.ts').default['handle'], false>
}
type LibraryIdGetHead = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/modules/library/list-videos-by-category/validator.ts')['validator']>>
  response: MakeTuyauResponse<import('../app/modules/library/list-videos-by-category/controller.ts').default['handle'], true>
}
type NotificationsGetHead = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/modules/notifications/get-notifications/validator.ts')['validator']>>
  response: MakeTuyauResponse<import('../app/modules/notifications/get-notifications/controller.ts').default['handle'], true>
}
type NotificationsCountGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/modules/notifications/get-count/controller.ts').default['handle'], false>
}
type NotificationsReadallPost = {
  request: unknown
  response: MakeTuyauResponse<import('../app/modules/notifications/mark-all-read/controller.ts').default['handle'], false>
}
type NotificationsIdPost = {
  request: unknown
  response: MakeTuyauResponse<import('../app/modules/notifications/mark-read/controller.ts').default['handle'], false>
}
type SkillsGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/modules/skills/get-skills/controller.ts').default['handle'], false>
}
type SportsGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/modules/sports/get-sports/controller.ts').default['handle'], false>
}
type StylesGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/modules/styles/get-styles/controller.ts').default['handle'], false>
}
type SubscriptionsStatusGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/modules/subscriptions/status/controller.ts').default['handle'], false>
}
type SubscriptionsCheckoutPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/modules/subscriptions/checkout/validator.ts')['schema']>>
  response: MakeTuyauResponse<import('../app/modules/subscriptions/checkout/controller.ts').default['handle'], true>
}
type SubscriptionsManagePost = {
  request: unknown
  response: MakeTuyauResponse<import('../app/modules/subscriptions/manage/controller.ts').default['handle'], false>
}
type StripeWebhookPost = {
  request: unknown
  response: MakeTuyauResponse<import('../app/modules/webhooks/stripe/controller.ts').default['handle'], false>
}
type ContactPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/modules/contact/contact-us/validator.ts')['schema']>>
  response: MakeTuyauResponse<import('../app/modules/contact/contact-us/controller.ts').default['handle'], true>
}
type FeedbackPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/modules/contact/feedback/validator.ts')['schema']>>
  response: MakeTuyauResponse<import('../app/modules/contact/feedback/controller.ts').default['handle'], true>
}
type DancersPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/modules/dancers/profile/create-dancer/validator.ts')['validator']>>
  response: MakeTuyauResponse<import('../app/modules/dancers/profile/create-dancer/controller.ts').default['handle'], true>
}
type DancersFiltersGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/modules/dancers/explore/get-dancer-filters/controller.ts').default['handle'], false>
}
type DancersGetHead = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/modules/dancers/explore/get-dancers/validator.ts')['validator']>>
  response: MakeTuyauResponse<import('../app/modules/dancers/explore/get-dancers/controller.ts').default['handle'], true>
}
type DancersMePatch = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/modules/dancers/profile/update-portfolio/validator.ts')['validator']>>
  response: MakeTuyauResponse<import('../app/modules/dancers/profile/update-portfolio/controller.ts').default['handle'], true>
}
type DancersMeSkillsGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/modules/dancers/profile/get-skills/controller.ts').default['handle'], false>
}
type DancersMeSkillsPatch = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/modules/dancers/profile/update-skills/validator.ts')['schema']>>
  response: MakeTuyauResponse<import('../app/modules/dancers/profile/update-skills/controller.ts').default['handle'], true>
}
type DancersMeStylesGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/modules/dancers/profile/get-styles/controller.ts').default['handle'], false>
}
type DancersMeStylesPatch = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/modules/dancers/profile/update-styles/validator.ts')['schema']>>
  response: MakeTuyauResponse<import('../app/modules/dancers/profile/update-styles/controller.ts').default['handle'], true>
}
type DancersMeSportsGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/modules/dancers/profile/get-sports/controller.ts').default['handle'], false>
}
type DancersMeSportsPatch = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/modules/dancers/profile/update-sports/validator.ts')['schema']>>
  response: MakeTuyauResponse<import('../app/modules/dancers/profile/update-sports/controller.ts').default['handle'], true>
}
type DancersMeFollowingGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/modules/dancers/engagement/get-following/controller.ts').default['handle'], false>
}
type DancersMeFollowingIdsGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/modules/dancers/engagement/get-following-ids/controller.ts').default['handle'], false>
}
type DancersMeFollowersGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/modules/dancers/engagement/get-followers/controller.ts').default['handle'], false>
}
type DancersMeChecklistGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/modules/dancers/profile/get-profile-checklist/controller.ts').default['handle'], false>
}
type DancersSubmissionsGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/modules/dancers/common-recruiting/get-submissions/controller.ts').default['handle'], false>
}
type DancersSubmissionsPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/modules/dancers/common-recruiting/create-submission/validator.ts')['schema']>>
  response: MakeTuyauResponse<import('../app/modules/dancers/common-recruiting/create-submission/controller.ts').default['handle'], true>
}
type DancersSubmissionsVideoPatch = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/modules/dancers/common-recruiting/edit-submission/validator.ts')['schema']>>
  response: MakeTuyauResponse<import('../app/modules/dancers/common-recruiting/edit-submission/controller.ts').default['handle'], true>
}
type DancersSubmissionsSchoolsGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/modules/dancers/common-recruiting/get-submission-schools/controller.ts').default['handle'], false>
}
type DancersSubmissionsVideoGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/modules/dancers/common-recruiting/get-submission-video/controller.ts').default['handle'], false>
}
type DancersIdGetHead = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/modules/dancers/profile/get-dancer/validator.ts')['validator']>>
  response: MakeTuyauResponse<import('../app/modules/dancers/profile/get-dancer/controller.ts').default['handle'], true>
}
type DancersIdFavoritePost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/modules/dancers/engagement/favorite/validator.ts')['schema']>>
  response: MakeTuyauResponse<import('../app/modules/dancers/engagement/favorite/controller.ts').default['handle'], true>
}
type DancersIdFavoriteDelete = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/modules/dancers/engagement/unfavorite/validator.ts')['schema']>>
  response: MakeTuyauResponse<import('../app/modules/dancers/engagement/unfavorite/controller.ts').default['handle'], true>
}
type DancersIdMetadataGetHead = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/modules/dancers/profile/get-dancer-metadata/validator.ts')['schema']>>
  response: MakeTuyauResponse<import('../app/modules/dancers/profile/get-dancer-metadata/controller.ts').default['handle'], true>
}
type DancersReferencesPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/modules/dancers/profile/create-reference/validator.ts')['schema']>>
  response: MakeTuyauResponse<import('../app/modules/dancers/profile/create-reference/controller.ts').default['handle'], true>
}
type DancersReferencesIdDelete = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/modules/dancers/profile/delete-reference/validator.ts')['schema']>>
  response: MakeTuyauResponse<import('../app/modules/dancers/profile/delete-reference/controller.ts').default['handle'], true>
}
type DancersReferencesIdPatch = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/modules/dancers/profile/update-reference/validator.ts')['schema']>>
  response: MakeTuyauResponse<import('../app/modules/dancers/profile/update-reference/controller.ts').default['handle'], true>
}
type DancersAchievementsAchievementsPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/modules/dancers/profile/create-achievement/validator.ts')['schema']>>
  response: MakeTuyauResponse<import('../app/modules/dancers/profile/create-achievement/controller.ts').default['handle'], true>
}
type DancersAchievementsAchievementsIdDelete = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/modules/dancers/profile/delete-achievement/validator.ts')['schema']>>
  response: MakeTuyauResponse<import('../app/modules/dancers/profile/delete-achievement/controller.ts').default['handle'], true>
}
type DancersAchievementsAchievementsIdPatch = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/modules/dancers/profile/update-achievement/validator.ts')['schema']>>
  response: MakeTuyauResponse<import('../app/modules/dancers/profile/update-achievement/controller.ts').default['handle'], true>
}
type EventsFiltersGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/modules/events/get-event-filters/controller.ts').default['handle'], false>
}
type EventsGetHead = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/modules/events/get-events/validator.ts')['validator']>>
  response: MakeTuyauResponse<import('../app/modules/events/get-events/controller.ts').default['handle'], true>
}
type EventsPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/modules/events/create-event/schema.ts')['createEventSchema']>>
  response: MakeTuyauResponse<import('../app/modules/events/create-event/controller.ts').default['handle'], true>
}
type EventsUpcomingGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/modules/events/get-upcoming-events/controller.ts').default['handle'], false>
}
type EventsGlobalGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/modules/events/get-global-events/controller.ts').default['handle'], false>
}
type EventsIdPatch = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/modules/events/edit-event/schema.ts')['editEventSchema']>>
  response: MakeTuyauResponse<import('../app/modules/events/edit-event/controller.ts').default['handle'], true>
}
type EventsIdGetHead = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/modules/events/get-event-by-id/validator.ts')['validator']>>
  response: MakeTuyauResponse<import('../app/modules/events/get-event-by-id/controller.ts').default['handle'], true>
}
type EventsIdDelete = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/modules/events/delete-event/schema.ts')['deleteEventSchema']>>
  response: MakeTuyauResponse<import('../app/modules/events/delete-event/controller.ts').default['handle'], true>
}
type EventsIdSavePost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/modules/events/save-event/validator.ts')['schema']>>
  response: MakeTuyauResponse<import('../app/modules/events/save-event/controller.ts').default['handle'], true>
}
type EventsIdUnsaveDelete = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/modules/events/unsave-event/validator.ts')['schema']>>
  response: MakeTuyauResponse<import('../app/modules/events/unsave-event/controller.ts').default['handle'], true>
}
type ImagesPresignPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/modules/images/upload-image/validator.ts')['schema']>>
  response: MakeTuyauResponse<import('../app/modules/images/upload-image/controller.ts').default['handle'], true>
}
type ImagesPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/modules/images/upload-profile-image/validator.ts')['schema']>>
  response: MakeTuyauResponse<import('../app/modules/images/upload-profile-image/controller.ts').default['handle'], true>
}
type ImagesIdDelete = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/modules/images/delete-image/validator.ts')['schema']>>
  response: MakeTuyauResponse<import('../app/modules/images/delete-image/controller.ts').default['handle'], true>
}
type SchoolsCheckavailabilityGetHead = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/modules/schools/check-name-availability/validator.ts')['validator']>>
  response: MakeTuyauResponse<import('../app/modules/schools/check-name-availability/controller.ts').default['handle'], true>
}
type SchoolsFiltersGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/modules/schools/get-school-filters/controller.ts').default['handle'], false>
}
type SchoolsGetHead = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/modules/schools/get-schools/validator.ts')['validator']>>
  response: MakeTuyauResponse<import('../app/modules/schools/get-schools/controller.ts').default['handle'], true>
}
type SchoolsRecommendedGetHead = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/modules/schools/get-recommended-programs/validator.ts')['schema']>>
  response: MakeTuyauResponse<import('../app/modules/schools/get-recommended-programs/controller.ts').default['handle'], true>
}
type SchoolsMePatch = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/modules/schools/update-program/validator.ts')['updateProgramSchema']>>
  response: MakeTuyauResponse<import('../app/modules/schools/update-program/controller.ts').default['handle'], true>
}
type SchoolsMeFollowersGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/modules/schools/get-followers/controller.ts').default['handle'], false>
}
type SchoolsMeFollowingIdsGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/modules/schools/get-following-ids/controller.ts').default['handle'], false>
}
type SchoolsMeFollowingGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/modules/schools/get-following/controller.ts').default['handle'], false>
}
type SchoolsMeFavoritesGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/modules/schools/get-favorites-data/controller.ts').default['handle'], false>
}
type SchoolsMeFavoritesIdPatch = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/modules/schools/update-favorite/validator.ts')['schema']>>
  response: MakeTuyauResponse<import('../app/modules/schools/update-favorite/controller.ts').default['handle'], true>
}
type SchoolsMeSkillsGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/modules/schools/get-skills/controller.ts').default['handle'], false>
}
type SchoolsMeSkillsPatch = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/modules/schools/update-skills/validator.ts')['schema']>>
  response: MakeTuyauResponse<import('../app/modules/schools/update-skills/controller.ts').default['handle'], true>
}
type SchoolsMeStylesGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/modules/schools/get-styles/controller.ts').default['handle'], false>
}
type SchoolsMeStylesPatch = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/modules/schools/update-styles/validator.ts')['schema']>>
  response: MakeTuyauResponse<import('../app/modules/schools/update-styles/controller.ts').default['handle'], true>
}
type SchoolsMeSportsGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/modules/schools/get-sports/controller.ts').default['handle'], false>
}
type SchoolsMeSportsPatch = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/modules/schools/update-sports/validator.ts')['schema']>>
  response: MakeTuyauResponse<import('../app/modules/schools/update-sports/controller.ts').default['handle'], true>
}
type SchoolsMeSubmissionsGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/modules/schools/get-submissions/controller.ts').default['handle'], false>
}
type SchoolsMeSubmissionsIdPatch = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/modules/schools/update-submission/validator.ts')['schema']>>
  response: MakeTuyauResponse<import('../app/modules/schools/update-submission/controller.ts').default['handle'], true>
}
type SchoolsMeViewdancerIdPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/modules/schools/view-dancer/validator.ts')['schema']>>
  response: MakeTuyauResponse<import('../app/modules/schools/view-dancer/controller.ts').default['handle'], true>
}
type SchoolsIdGetHead = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/modules/schools/get-school/validator.ts')['schema']>>
  response: MakeTuyauResponse<import('../app/modules/schools/get-school/controller.ts').default['handle'], true>
}
type SchoolsIdFollowPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/modules/schools/follow/validator.ts')['schema']>>
  response: MakeTuyauResponse<import('../app/modules/schools/follow/controller.ts').default['handle'], true>
}
type SchoolsIdFollowDelete = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/modules/schools/unfollow/validator.ts')['schema']>>
  response: MakeTuyauResponse<import('../app/modules/schools/unfollow/controller.ts').default['handle'], true>
}
type SchoolsIdMetadataGetHead = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/modules/schools/get-school-metadata/validator.ts')['schema']>>
  response: MakeTuyauResponse<import('../app/modules/schools/get-school-metadata/controller.ts').default['handle'], true>
}
type SchoolsIdInterestPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/modules/schools/show-interest/validator.ts')['schema']>>
  response: MakeTuyauResponse<import('../app/modules/schools/show-interest/controller.ts').default['handle'], true>
}
type UsersCheckavailabilityGetHead = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/modules/users/check-availability/validator.ts')['validator']>>
  response: MakeTuyauResponse<import('../app/modules/users/check-availability/controller.ts').default['handle'], true>
}
type UsersAccountGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/modules/users/get-account/controller.ts').default['handle'], false>
}
type UsersAccountPatch = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/modules/users/update-account/validator.ts')['schema']>>
  response: MakeTuyauResponse<import('../app/modules/users/update-account/controller.ts').default['handle'], true>
}
type UsersAccountDelete = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/modules/users/delete-account/validator.ts')['schema']>>
  response: MakeTuyauResponse<import('../app/modules/users/delete-account/controller.ts').default['handle'], true>
}
type UsersAvatarPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/modules/users/update-avatar/validator.ts')['schema']>>
  response: MakeTuyauResponse<import('../app/modules/users/update-avatar/controller.ts').default['handle'], true>
}
type UsersActivityGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/modules/users/get-activity/controller.ts').default['handle'], false>
}
type VideosPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/modules/videos/upload-profile-video/validator.ts')['schema']>>
  response: MakeTuyauResponse<import('../app/modules/videos/upload-profile-video/controller.ts').default['handle'], true>
}
type VideosIdDelete = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/modules/videos/delete-video/validator.ts')['schema']>>
  response: MakeTuyauResponse<import('../app/modules/videos/delete-video/controller.ts').default['handle'], true>
}
export interface ApiDefinition {
  'admin': {
    'schools': {
      ':id': {
        'approve': {
          '$url': {
          };
          '$post': AdminSchoolsIdApprovePost;
        };
      };
    };
  };
  'application': {
    '$url': {
    };
    '$get': ApplicationGetHead;
    '$head': ApplicationGetHead;
    '$post': ApplicationPost;
    '$patch': ApplicationPatch;
  };
  'auth': {
    'signup': {
      '$url': {
      };
      '$post': AuthSignupPost;
    };
    'login': {
      '$url': {
      };
      '$post': AuthLoginPost;
    };
    'logout': {
      '$url': {
      };
      '$post': AuthLogoutPost;
    };
    'session': {
      '$url': {
      };
      '$get': AuthSessionGetHead;
      '$head': AuthSessionGetHead;
    };
    'password': {
      'change': {
        '$url': {
        };
        '$post': AuthPasswordChangePost;
      };
      'forgot': {
        '$url': {
        };
        '$post': AuthPasswordForgotPost;
      };
      'reset': {
        '$url': {
        };
        '$post': AuthPasswordResetPost;
      };
    };
  };
  'blog': {
    '$url': {
    };
    '$get': BlogGetHead;
    '$head': BlogGetHead;
  };
  'feed': {
    '$url': {
    };
    '$get': FeedGetHead;
    '$head': FeedGetHead;
  };
  'health': {
    '$url': {
    };
    '$get': HealthGetHead;
    '$head': HealthGetHead;
  };
  'library': {
    '$url': {
    };
    '$get': LibraryGetHead;
    '$head': LibraryGetHead;
    ':category': {
      '$url': {
      };
      '$get': LibraryIdGetHead;
      '$head': LibraryIdGetHead;
    };
  };
  'notifications': {
    '$url': {
    };
    '$get': NotificationsGetHead;
    '$head': NotificationsGetHead;
    'count': {
      '$url': {
      };
      '$get': NotificationsCountGetHead;
      '$head': NotificationsCountGetHead;
    };
    'read-all': {
      '$url': {
      };
      '$post': NotificationsReadallPost;
    };
    ':id': {
      '$url': {
      };
      '$post': NotificationsIdPost;
    };
  };
  'skills': {
    '$url': {
    };
    '$get': SkillsGetHead;
    '$head': SkillsGetHead;
  };
  'sports': {
    '$url': {
    };
    '$get': SportsGetHead;
    '$head': SportsGetHead;
  };
  'styles': {
    '$url': {
    };
    '$get': StylesGetHead;
    '$head': StylesGetHead;
  };
  'subscriptions': {
    'status': {
      '$url': {
      };
      '$get': SubscriptionsStatusGetHead;
      '$head': SubscriptionsStatusGetHead;
    };
    'checkout': {
      '$url': {
      };
      '$post': SubscriptionsCheckoutPost;
    };
    'manage': {
      '$url': {
      };
      '$post': SubscriptionsManagePost;
    };
  };
  'stripe': {
    'webhook': {
      '$url': {
      };
      '$post': StripeWebhookPost;
    };
  };
  'contact': {
    '$url': {
    };
    '$post': ContactPost;
  };
  'feedback': {
    '$url': {
    };
    '$post': FeedbackPost;
  };
  'dancers': {
    '$url': {
    };
    '$post': DancersPost;
    'filters': {
      '$url': {
      };
      '$get': DancersFiltersGetHead;
      '$head': DancersFiltersGetHead;
    };
    '$get': DancersGetHead;
    '$head': DancersGetHead;
    'me': {
      '$url': {
      };
      '$patch': DancersMePatch;
      'skills': {
        '$url': {
        };
        '$get': DancersMeSkillsGetHead;
        '$head': DancersMeSkillsGetHead;
        '$patch': DancersMeSkillsPatch;
      };
      'styles': {
        '$url': {
        };
        '$get': DancersMeStylesGetHead;
        '$head': DancersMeStylesGetHead;
        '$patch': DancersMeStylesPatch;
      };
      'sports': {
        '$url': {
        };
        '$get': DancersMeSportsGetHead;
        '$head': DancersMeSportsGetHead;
        '$patch': DancersMeSportsPatch;
      };
      'following': {
        '$url': {
        };
        '$get': DancersMeFollowingGetHead;
        '$head': DancersMeFollowingGetHead;
        'ids': {
          '$url': {
          };
          '$get': DancersMeFollowingIdsGetHead;
          '$head': DancersMeFollowingIdsGetHead;
        };
      };
      'followers': {
        '$url': {
        };
        '$get': DancersMeFollowersGetHead;
        '$head': DancersMeFollowersGetHead;
      };
      'checklist': {
        '$url': {
        };
        '$get': DancersMeChecklistGetHead;
        '$head': DancersMeChecklistGetHead;
      };
    };
    'submissions': {
      '$url': {
      };
      '$get': DancersSubmissionsGetHead;
      '$head': DancersSubmissionsGetHead;
      '$post': DancersSubmissionsPost;
      'video': {
        '$url': {
        };
        '$patch': DancersSubmissionsVideoPatch;
        '$get': DancersSubmissionsVideoGetHead;
        '$head': DancersSubmissionsVideoGetHead;
      };
      'schools': {
        '$url': {
        };
        '$get': DancersSubmissionsSchoolsGetHead;
        '$head': DancersSubmissionsSchoolsGetHead;
      };
    };
    ':username': {
      '$url': {
      };
      '$get': DancersIdGetHead;
      '$head': DancersIdGetHead;
    };
    ':id': {
      'favorite': {
        '$url': {
        };
        '$post': DancersIdFavoritePost;
        '$delete': DancersIdFavoriteDelete;
      };
      'metadata': {
        '$url': {
        };
        '$get': DancersIdMetadataGetHead;
        '$head': DancersIdMetadataGetHead;
      };
    };
    'references': {
      '$url': {
      };
      '$post': DancersReferencesPost;
      ':id': {
        '$url': {
        };
        '$delete': DancersReferencesIdDelete;
        '$patch': DancersReferencesIdPatch;
      };
    };
    'achievements': {
      'achievements': {
        '$url': {
        };
        '$post': DancersAchievementsAchievementsPost;
        ':id': {
          '$url': {
          };
          '$delete': DancersAchievementsAchievementsIdDelete;
          '$patch': DancersAchievementsAchievementsIdPatch;
        };
      };
    };
  };
  'events': {
    'filters': {
      '$url': {
      };
      '$get': EventsFiltersGetHead;
      '$head': EventsFiltersGetHead;
    };
    '$url': {
    };
    '$get': EventsGetHead;
    '$head': EventsGetHead;
    '$post': EventsPost;
    'upcoming': {
      '$url': {
      };
      '$get': EventsUpcomingGetHead;
      '$head': EventsUpcomingGetHead;
    };
    'global': {
      '$url': {
      };
      '$get': EventsGlobalGetHead;
      '$head': EventsGlobalGetHead;
    };
    ':id': {
      '$url': {
      };
      '$patch': EventsIdPatch;
      '$get': EventsIdGetHead;
      '$head': EventsIdGetHead;
      '$delete': EventsIdDelete;
      'save': {
        '$url': {
        };
        '$post': EventsIdSavePost;
      };
      'unsave': {
        '$url': {
        };
        '$delete': EventsIdUnsaveDelete;
      };
    };
  };
  'images': {
    'presign': {
      '$url': {
      };
      '$post': ImagesPresignPost;
    };
    '$url': {
    };
    '$post': ImagesPost;
    ':id': {
      '$url': {
      };
      '$delete': ImagesIdDelete;
    };
  };
  'schools': {
    'check-availability': {
      '$url': {
      };
      '$get': SchoolsCheckavailabilityGetHead;
      '$head': SchoolsCheckavailabilityGetHead;
    };
    'filters': {
      '$url': {
      };
      '$get': SchoolsFiltersGetHead;
      '$head': SchoolsFiltersGetHead;
    };
    '$url': {
    };
    '$get': SchoolsGetHead;
    '$head': SchoolsGetHead;
    'recommended': {
      '$url': {
      };
      '$get': SchoolsRecommendedGetHead;
      '$head': SchoolsRecommendedGetHead;
    };
    'me': {
      '$url': {
      };
      '$patch': SchoolsMePatch;
      'followers': {
        '$url': {
        };
        '$get': SchoolsMeFollowersGetHead;
        '$head': SchoolsMeFollowersGetHead;
      };
      'following': {
        'ids': {
          '$url': {
          };
          '$get': SchoolsMeFollowingIdsGetHead;
          '$head': SchoolsMeFollowingIdsGetHead;
        };
        '$url': {
        };
        '$get': SchoolsMeFollowingGetHead;
        '$head': SchoolsMeFollowingGetHead;
      };
      'favorites': {
        '$url': {
        };
        '$get': SchoolsMeFavoritesGetHead;
        '$head': SchoolsMeFavoritesGetHead;
        ':id': {
          '$url': {
          };
          '$patch': SchoolsMeFavoritesIdPatch;
        };
      };
      'skills': {
        '$url': {
        };
        '$get': SchoolsMeSkillsGetHead;
        '$head': SchoolsMeSkillsGetHead;
        '$patch': SchoolsMeSkillsPatch;
      };
      'styles': {
        '$url': {
        };
        '$get': SchoolsMeStylesGetHead;
        '$head': SchoolsMeStylesGetHead;
        '$patch': SchoolsMeStylesPatch;
      };
      'sports': {
        '$url': {
        };
        '$get': SchoolsMeSportsGetHead;
        '$head': SchoolsMeSportsGetHead;
        '$patch': SchoolsMeSportsPatch;
      };
      'submissions': {
        '$url': {
        };
        '$get': SchoolsMeSubmissionsGetHead;
        '$head': SchoolsMeSubmissionsGetHead;
        ':id': {
          '$url': {
          };
          '$patch': SchoolsMeSubmissionsIdPatch;
        };
      };
      'view-dancer': {
        ':id': {
          '$url': {
          };
          '$post': SchoolsMeViewdancerIdPost;
        };
      };
    };
    ':username': {
      '$url': {
      };
      '$get': SchoolsIdGetHead;
      '$head': SchoolsIdGetHead;
    };
    ':id': {
      'follow': {
        '$url': {
        };
        '$post': SchoolsIdFollowPost;
        '$delete': SchoolsIdFollowDelete;
      };
      'metadata': {
        '$url': {
        };
        '$get': SchoolsIdMetadataGetHead;
        '$head': SchoolsIdMetadataGetHead;
      };
      'interest': {
        '$url': {
        };
        '$post': SchoolsIdInterestPost;
      };
    };
  };
  'users': {
    'check-availability': {
      '$url': {
      };
      '$get': UsersCheckavailabilityGetHead;
      '$head': UsersCheckavailabilityGetHead;
    };
    'account': {
      '$url': {
      };
      '$get': UsersAccountGetHead;
      '$head': UsersAccountGetHead;
      '$patch': UsersAccountPatch;
      '$delete': UsersAccountDelete;
    };
    'avatar': {
      '$url': {
      };
      '$post': UsersAvatarPost;
    };
    'activity': {
      '$url': {
      };
      '$get': UsersActivityGetHead;
      '$head': UsersActivityGetHead;
    };
  };
  'videos': {
    '$url': {
    };
    '$post': VideosPost;
    ':id': {
      '$url': {
      };
      '$delete': VideosIdDelete;
    };
  };
}
const routes = [
] as const;
export const api = {
  routes,
  definition: {} as ApiDefinition
}
