// @ts-nocheck
/* eslint-disable */
// --------------------------------------------------
// This file is auto-generated by Tuyau. Do not edit manually !
// --------------------------------------------------

import type { MakeTuyauRequest, MakeTuyauResponse } from '@tuyau/utils/types'
import type { InferInput } from '@vinejs/vine/types'

type AuthRegisterPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/features/auth/register/register.validator.ts')['RegisterValidator']>>
  response: MakeTuyauResponse<import('../app/features/auth/register/register.controller.ts').default['handle'], true>
}
type AuthLoginPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/features/auth/login/login.validator.ts')['LoginValidator']>>
  response: MakeTuyauResponse<import('../app/features/auth/login/login.controller.ts').default['handle'], true>
}
type AuthLogoutPost = {
  request: unknown
  response: MakeTuyauResponse<import('../app/features/auth/logout/logout.controller.ts').default['handle'], false>
}
export interface ApiDefinition {
  'auth': {
    'register': {
      '$url': {
      };
      '$post': AuthRegisterPost;
    };
    'login': {
      '$url': {
      };
      '$post': AuthLoginPost;
    };
    'logout': {
      '$url': {
      };
      '$post': AuthLogoutPost;
    };
  };
}
const routes = [
] as const;
export const api = {
  routes,
  definition: {} as ApiDefinition
}
