import { type Filter } from "#shared/types/filters";

type SchoolParamKey =
  | "name"
  | "commonRecruitingApplication"
  | "division"
  | "gpaRange"
  | "location"
  | "sports"
  | "styles"
  | "hasUpcomingEvents"
  | "teamSelection"
  | "teamType";

type DancerParamKey =
  | "name"
  | "commonRecruitingApplication"
  | "division"
  | "gpaRange"
  | "location"
  | "sports"
  | "styles"
  | "hasUpcomingEvents"
  | "teamSelection"
  | "teamType";

export const schoolFilters: Filter<SchoolParamKey>[] = [
  {
    label: "School Name",
    id: "school-name",
    type: "input",
    paramKey: "name",
  },
  {
    label: "Common Recruiting Application",
    id: "common-recruiting-application",
    type: "toggle",
    paramKey: "commonRecruitingApplication",
  },
  {
    label: "Division",
    id: "division",
    type: "multi-select",
    paramKey: "division",
    options: [
      { label: "Division IA", value: "division-ia" },
      { label: "Division I", value: "division-i" },
      { label: "Division II", value: "division-ii" },
      { label: "Division III", value: "division-iii" },
      { label: "NAIA", value: "naia" },
    ],
  },
  {
    label: "GPA Range",
    id: "gpa-range",
    type: "range",
    paramKey: "gpaRange",
    options: [
      { value: "4", label: "4+" },
      { value: "3.75", label: "3.75+" },
      { value: "3.5", label: "3.5+" },
      { value: "3.25", label: "3.25+" },
      { value: "3.0", label: "3.0+" },
      { value: "2.75", label: "2.75+" },
      { value: "2.5", label: "2.5+" },
      { value: "2.25", label: "2.25+" },
    ],
  },
  {
    label: "Location",
    id: "location",
    type: "select",
    paramKey: "location",
    options: [
      { label: "Alabama", value: "alabama" },
      { label: "Alaska", value: "alaska" },
      { label: "Arizona", value: "arizona" },
      { label: "Arkansas", value: "arkansas" },
      { label: "California", value: "california" },
      { label: "Colorado", value: "colorado" },
      { label: "Connecticut", value: "connecticut" },
      { label: "Delaware", value: "delaware" },
      { label: "Florida", value: "florida" },
      { label: "Georgia", value: "georgia" },
      { label: "Hawaii", value: "hawaii" },
      { label: "Idaho", value: "idaho" },
      { label: "Illinois", value: "illinois" },
      { label: "Indiana", value: "indiana" },
      { label: "Iowa", value: "iowa" },
      { label: "Kansas", value: "kansas" },
      { label: "Kentucky", value: "kentucky" },
      { label: "Louisiana", value: "louisiana" },
      { label: "Maine", value: "maine" },
      { label: "Maryland", value: "maryland" },
      { label: "Massachusetts", value: "massachusetts" },
      { label: "Michigan", value: "michigan" },
      { label: "Minnesota", value: "minnesota" },
      { label: "Mississippi", value: "mississippi" },
      { label: "Missouri", value: "missouri" },
      { label: "Montana", value: "Montana" },
      { label: "Nebraska", value: "nebraska" },
      { label: "Nevada", value: "nevada" },
      { label: "New Hampshire", value: "new-hampshire" },
      { label: "New Jersey", value: "new-jersey" },
      { label: "New Mexico", value: "new-mexico" },
      { label: "New York", value: "new-york" },
      { label: "North Carolina", value: "north-carolina" },
      { label: "North Dakota", value: "north-dakota" },
      { label: "Ohio", value: "ohio" },
      { label: "Oklahoma", value: "oklahoma" },
      { label: "Oregon", value: "oregon" },
      { label: "Pennsylvania", value: "pennsylvania" },
      { label: "Rhode Island", value: "rhode-island" },
      { label: "South Carolina", value: "south-carolina" },
      { label: "South Dakota", value: "south-dakota" },
      { label: "Tennessee", value: "tennessee" },
      { label: "Texas", value: "texas" },
      { label: "Utah", value: "utah" },
      { label: "Vermont", value: "vermont" },
      { label: "Virginia", value: "virginia" },
      { label: "Washington", value: "washington" },
      { label: "West Virginia", value: "west-virginia" },
      { label: "Wisconsin", value: "wisconsin" },
      { label: "Wyoming", value: "wyoming" },
    ],
  },
  {
    label: "Sports",
    id: "sports",
    type: "multi-select",
    paramKey: "sports",
    options: [
      { label: "Football", value: "football" },
      { label: "Basketball", value: "basketball" },
      { label: "Volleyball", value: "volleyball" },
      { label: "Soccer", value: "soccer" },
      { label: "Baseball", value: "baseball" },
      { label: "Gymnastics", value: "gymnastics" },
      { label: "Swim", value: "swim" },
      { label: "Tennis", value: "tennis" },
      { label: "Hockey", value: "hockey" },
      { label: "Lacrosse", value: "lacrosse" },
      { label: "Golf", value: "golf" },
      { label: "Skiing", value: "skiing" },
      { label: "Wrestling", value: "wrestling" },
      { label: "Water Polo", value: "water-polo" },
      { label: "Track and Field", value: "track-and-field" },
      { label: "Softball", value: "softball" },
      { label: "Rowing", value: "rowing" },
      { label: "Other", value: "other" },
    ],
  },
  {
    label: "Styles",
    id: "styles",
    type: "multi-select",
    paramKey: "styles",
    options: [
      { value: "hip-hop", label: "Hip Hop" },
      { value: "jazz", label: "Jazz" },
      { value: "pom", label: "Pom" },
      { value: "game-day", label: "Game Day" },
      { value: "kick", label: "Kick" },
      { value: "military", label: "Military" },
      { value: "lyrical-comtemporary", label: "Lyrical/Comtemporary" },
      { value: "team-performance", label: "Team Performance" },
      { value: "non-competitive", label: "Non-Competitive" },
    ],
  },
  {
    label: "Upcoming Events",
    id: "upcoming-events",
    type: "toggle",
    paramKey: "hasUpcomingEvents",
  },
  {
    label: "Team Selection",
    id: "team-selection",
    type: "input",
    paramKey: "teamSelection",
  },
  {
    label: "Team Type",
    id: "team-type",
    type: "input",
    paramKey: "teamType",
  },
];

export const dancerFilters: Filter<DancerParamKey>[] = [
  {
    label: "School Name",
    id: "school-name",
    type: "input",
    paramKey: "name",
  },
  {
    label: "Common Recruiting Application",
    id: "common-recruiting-application",
    type: "toggle",
    paramKey: "commonRecruitingApplication",
  },
  {
    label: "Division",
    id: "division",
    type: "multi-select",
    paramKey: "division",
    options: [
      { label: "Division IA", value: "division-ia" },
      { label: "Division I", value: "division-i" },
      { label: "Division II", value: "division-ii" },
      { label: "Division III", value: "division-iii" },
      { label: "NAIA", value: "naia" },
    ],
  },
  {
    label: "GPA Range",
    id: "gpa-range",
    type: "range",
    paramKey: "gpaRange",
    options: [
      { value: "4", label: "4+" },
      { value: "3.75", label: "3.75+" },
      { value: "3.5", label: "3.5+" },
      { value: "3.25", label: "3.25+" },
      { value: "3.0", label: "3.0+" },
      { value: "2.75", label: "2.75+" },
      { value: "2.5", label: "2.5+" },
      { value: "2.25", label: "2.25+" },
    ],
  },
  {
    label: "Location",
    id: "location",
    type: "select",
    paramKey: "location",
    options: [
      { label: "Alabama", value: "alabama" },
      { label: "Alaska", value: "alaska" },
      { label: "Arizona", value: "arizona" },
      { label: "Arkansas", value: "arkansas" },
      { label: "California", value: "california" },
      { label: "Colorado", value: "colorado" },
      { label: "Connecticut", value: "connecticut" },
      { label: "Delaware", value: "delaware" },
      { label: "Florida", value: "florida" },
      { label: "Georgia", value: "georgia" },
      { label: "Hawaii", value: "hawaii" },
      { label: "Idaho", value: "idaho" },
      { label: "Illinois", value: "illinois" },
      { label: "Indiana", value: "indiana" },
      { label: "Iowa", value: "iowa" },
      { label: "Kansas", value: "kansas" },
      { label: "Kentucky", value: "kentucky" },
      { label: "Louisiana", value: "louisiana" },
      { label: "Maine", value: "maine" },
      { label: "Maryland", value: "maryland" },
      { label: "Massachusetts", value: "massachusetts" },
      { label: "Michigan", value: "michigan" },
      { label: "Minnesota", value: "minnesota" },
      { label: "Mississippi", value: "mississippi" },
      { label: "Missouri", value: "missouri" },
      { label: "Montana", value: "Montana" },
      { label: "Nebraska", value: "nebraska" },
      { label: "Nevada", value: "nevada" },
      { label: "New Hampshire", value: "new-hampshire" },
      { label: "New Jersey", value: "new-jersey" },
      { label: "New Mexico", value: "new-mexico" },
      { label: "New York", value: "new-york" },
      { label: "North Carolina", value: "north-carolina" },
      { label: "North Dakota", value: "north-dakota" },
      { label: "Ohio", value: "ohio" },
      { label: "Oklahoma", value: "oklahoma" },
      { label: "Oregon", value: "oregon" },
      { label: "Pennsylvania", value: "pennsylvania" },
      { label: "Rhode Island", value: "rhode-island" },
      { label: "South Carolina", value: "south-carolina" },
      { label: "South Dakota", value: "south-dakota" },
      { label: "Tennessee", value: "tennessee" },
      { label: "Texas", value: "texas" },
      { label: "Utah", value: "utah" },
      { label: "Vermont", value: "vermont" },
      { label: "Virginia", value: "virginia" },
      { label: "Washington", value: "washington" },
      { label: "West Virginia", value: "west-virginia" },
      { label: "Wisconsin", value: "wisconsin" },
      { label: "Wyoming", value: "wyoming" },
    ],
  },
  {
    label: "Sports",
    id: "sports",
    type: "multi-select",
    paramKey: "sports",
    options: [
      { label: "Football", value: "football" },
      { label: "Basketball", value: "basketball" },
      { label: "Volleyball", value: "volleyball" },
      { label: "Soccer", value: "soccer" },
      { label: "Baseball", value: "baseball" },
      { label: "Gymnastics", value: "gymnastics" },
      { label: "Swim", value: "swim" },
      { label: "Tennis", value: "tennis" },
      { label: "Hockey", value: "hockey" },
      { label: "Lacrosse", value: "lacrosse" },
      { label: "Golf", value: "golf" },
      { label: "Skiing", value: "skiing" },
      { label: "Wrestling", value: "wrestling" },
      { label: "Water Polo", value: "water-polo" },
      { label: "Track and Field", value: "track-and-field" },
      { label: "Softball", value: "softball" },
      { label: "Rowing", value: "rowing" },
      { label: "Other", value: "other" },
    ],
  },
  {
    label: "Styles",
    id: "styles",
    type: "multi-select",
    paramKey: "styles",
    options: [
      { value: "hip-hop", label: "Hip Hop" },
      { value: "jazz", label: "Jazz" },
      { value: "pom", label: "Pom" },
      { value: "game-day", label: "Game Day" },
      { value: "kick", label: "Kick" },
      { value: "military", label: "Military" },
      { value: "lyrical-comtemporary", label: "Lyrical/Comtemporary" },
      { value: "team-performance", label: "Team Performance" },
      { value: "non-competitive", label: "Non-Competitive" },
    ],
  },
  {
    label: "Upcoming Events",
    id: "upcoming-events",
    type: "toggle",
    paramKey: "hasUpcomingEvents",
  },
  {
    label: "Team Selection",
    id: "team-selection",
    type: "input",
    paramKey: "teamSelection",
  },
  {
    label: "Team Type",
    id: "team-type",
    type: "input",
    paramKey: "teamType",
  },
];
