###
GET http://localhost:3333/auth/session
Content-Type: application/json

###
POST http://localhost:3333/auth/logout
Content-Type: application/json

###
POST http://localhost:3333/auth/login
Content-Type: application/json

{
    "email": "camtredoux+bobby@GMAIL.com",
    "password": "Cam"
}

###
POST http://localhost:3333/auth/signup
Content-Type: application/json

{
    "email": "   CAMTREDOUX.dev1+bobby@gmail.com   ",
    "password": "Cameron@13",
    "accountType": "dancer",
    "phone": "123456789012",
    "confirmPassword": "Cameron@13",
    "username": "  camtredoux1  ",
    "firstName": "  Cameron  ",
    "lastName": "  Tredoux",
    "termsChecked": true
}

###
POST http://localhost:3333/auth/refresh-session
Content-Type: application/json

###
POST http://localhost:3333/auth/test
Content-Type: application/json

###
GET http://localhost:3333/health
Content-Type: application/json
X-Health-Secret: hd0XF5UjZw6n9gbwmy3mleNGAqnYT77VLmSimeDflcw=
