GET http://localhost:3333/user
###
POST http://localhost:3333/auth/logout
Content-Type: application/json
###
POST http://localhost:3333/auth/login
Content-Type: application/json

{
    "email": "camtredoux@gmail.com",
    "password": "Cameron@1"
}
###
POST http://localhost:3333/auth/register
Content-Type: application/json

{
    "email": "camtredoux@gmail.com",
    "password": "password",
    "username": "camtredoux",
    "firstName": "Cameron",
    "lastName": "Tredoux",
    "image": "asd"
}
