###
GET http://localhost:3333/auth/session

###
POST http://localhost:3333/auth/logout
Content-Type: application/json

###
POST http://localhost:3333/auth/login
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "password"
}

###
POST http://localhost:3333/auth/signup
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "password",
    "confirmPassword": "password",
    "username": "camtredoux",
    "firstName": "Cameron",
    "lastName": "Tredoux",
    "termsChecked": true
}

###
POST http://localhost:3333/auth/refresh-session
Content-Type: application/json

###
POST http://localhost:3333/auth/test
Content-Type: application/json
