/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteRouteImport } from './routes/_onboarding/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AdminRouteRouteImport } from './routes/_admin/route'
import { Route as ApproutesIndexRouteImport } from './routes/_app/(routes)/index'
import { Route as AuthroutesLoginRouteImport } from './routes/_auth/(routes)/login'
import { Route as ApproutesUnauthorizedRouteImport } from './routes/_app/(routes)/unauthorized'
import { Route as ApproutesResourcesRouteImport } from './routes/_app/(routes)/resources'
import { Route as ApproutesRecruitingRouteImport } from './routes/_app/(routes)/recruiting'
import { Route as ApproutesLogoutRouteImport } from './routes/_app/(routes)/logout'
import { Route as ApproutesExploreRouteImport } from './routes/_app/(routes)/explore'
import { Route as ApproutesUsernameRouteImport } from './routes/_app/(routes)/$username'
import { Route as AdminroutesDashboardRouteImport } from './routes/_admin/(routes)/dashboard'
import { Route as OnboardingroutesOnboardingIndexRouteImport } from './routes/_onboarding/(routes)/onboarding/index'
import { Route as AuthroutesSignupIndexRouteImport } from './routes/_auth/(routes)/signup/index'
import { Route as AuthroutesResetIndexRouteImport } from './routes/_auth/(routes)/reset/index'
import { Route as ApproutesSettingsIndexRouteImport } from './routes/_app/(routes)/settings/index'
import { Route as ApproutesEventsIndexRouteImport } from './routes/_app/(routes)/events/index'
import { Route as AuthroutesSignupTypeRouteImport } from './routes/_auth/(routes)/signup/$type'
import { Route as AuthroutesResetTokenIdRouteImport } from './routes/_auth/(routes)/reset/$tokenId'
import { Route as ApproutesSettingsProfileRouteImport } from './routes/_app/(routes)/settings/profile'
import { Route as ApproutesSettingsMediaRouteImport } from './routes/_app/(routes)/settings/media'
import { Route as ApproutesSettingsGeneralRouteImport } from './routes/_app/(routes)/settings/general'
import { Route as ApproutesEventsEventIdRouteImport } from './routes/_app/(routes)/events/$eventId'
import { Route as AdminroutesDashboardMetricsRouteImport } from './routes/_admin/(routes)/dashboard/metrics'
import { Route as AdminroutesDashboardAssetsRouteImport } from './routes/_admin/(routes)/dashboard/assets'
import { Route as ApproutesSchoolUsernameIndexRouteImport } from './routes/_app/(routes)/school/$username/index'
import { Route as ApproutesSchoolUsernameRecruitingRouteImport } from './routes/_app/(routes)/school/$username/recruiting'

const OnboardingRouteRoute = OnboardingRouteRouteImport.update({
  id: '/_onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApproutesIndexRoute = ApproutesIndexRouteImport.update({
  id: '/(routes)/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AuthroutesLoginRoute = AuthroutesLoginRouteImport.update({
  id: '/(routes)/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ApproutesUnauthorizedRoute = ApproutesUnauthorizedRouteImport.update({
  id: '/(routes)/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApproutesResourcesRoute = ApproutesResourcesRouteImport.update({
  id: '/(routes)/resources',
  path: '/resources',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApproutesRecruitingRoute = ApproutesRecruitingRouteImport.update({
  id: '/(routes)/recruiting',
  path: '/recruiting',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApproutesLogoutRoute = ApproutesLogoutRouteImport.update({
  id: '/(routes)/logout',
  path: '/logout',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApproutesExploreRoute = ApproutesExploreRouteImport.update({
  id: '/(routes)/explore',
  path: '/explore',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApproutesUsernameRoute = ApproutesUsernameRouteImport.update({
  id: '/(routes)/$username',
  path: '/$username',
  getParentRoute: () => AppRouteRoute,
} as any)
const AdminroutesDashboardRoute = AdminroutesDashboardRouteImport.update({
  id: '/(routes)/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRouteRoute,
} as any)
const OnboardingroutesOnboardingIndexRoute =
  OnboardingroutesOnboardingIndexRouteImport.update({
    id: '/(routes)/onboarding/',
    path: '/onboarding/',
    getParentRoute: () => OnboardingRouteRoute,
  } as any)
const AuthroutesSignupIndexRoute = AuthroutesSignupIndexRouteImport.update({
  id: '/(routes)/signup/',
  path: '/signup/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthroutesResetIndexRoute = AuthroutesResetIndexRouteImport.update({
  id: '/(routes)/reset/',
  path: '/reset/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ApproutesSettingsIndexRoute = ApproutesSettingsIndexRouteImport.update({
  id: '/(routes)/settings/',
  path: '/settings/',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApproutesEventsIndexRoute = ApproutesEventsIndexRouteImport.update({
  id: '/(routes)/events/',
  path: '/events/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AuthroutesSignupTypeRoute = AuthroutesSignupTypeRouteImport.update({
  id: '/(routes)/signup/$type',
  path: '/signup/$type',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthroutesResetTokenIdRoute = AuthroutesResetTokenIdRouteImport.update({
  id: '/(routes)/reset/$tokenId',
  path: '/reset/$tokenId',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ApproutesSettingsProfileRoute =
  ApproutesSettingsProfileRouteImport.update({
    id: '/(routes)/settings/profile',
    path: '/settings/profile',
    getParentRoute: () => AppRouteRoute,
  } as any)
const ApproutesSettingsMediaRoute = ApproutesSettingsMediaRouteImport.update({
  id: '/(routes)/settings/media',
  path: '/settings/media',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApproutesSettingsGeneralRoute =
  ApproutesSettingsGeneralRouteImport.update({
    id: '/(routes)/settings/general',
    path: '/settings/general',
    getParentRoute: () => AppRouteRoute,
  } as any)
const ApproutesEventsEventIdRoute = ApproutesEventsEventIdRouteImport.update({
  id: '/(routes)/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AdminroutesDashboardMetricsRoute =
  AdminroutesDashboardMetricsRouteImport.update({
    id: '/metrics',
    path: '/metrics',
    getParentRoute: () => AdminroutesDashboardRoute,
  } as any)
const AdminroutesDashboardAssetsRoute =
  AdminroutesDashboardAssetsRouteImport.update({
    id: '/assets',
    path: '/assets',
    getParentRoute: () => AdminroutesDashboardRoute,
  } as any)
const ApproutesSchoolUsernameIndexRoute =
  ApproutesSchoolUsernameIndexRouteImport.update({
    id: '/(routes)/school/$username/',
    path: '/school/$username/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const ApproutesSchoolUsernameRecruitingRoute =
  ApproutesSchoolUsernameRecruitingRouteImport.update({
    id: '/(routes)/school/$username/recruiting',
    path: '/school/$username/recruiting',
    getParentRoute: () => AppRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ApproutesIndexRoute
  '/dashboard': typeof AdminroutesDashboardRouteWithChildren
  '/$username': typeof ApproutesUsernameRoute
  '/explore': typeof ApproutesExploreRoute
  '/logout': typeof ApproutesLogoutRoute
  '/recruiting': typeof ApproutesRecruitingRoute
  '/resources': typeof ApproutesResourcesRoute
  '/unauthorized': typeof ApproutesUnauthorizedRoute
  '/login': typeof AuthroutesLoginRoute
  '/dashboard/assets': typeof AdminroutesDashboardAssetsRoute
  '/dashboard/metrics': typeof AdminroutesDashboardMetricsRoute
  '/events/$eventId': typeof ApproutesEventsEventIdRoute
  '/settings/general': typeof ApproutesSettingsGeneralRoute
  '/settings/media': typeof ApproutesSettingsMediaRoute
  '/settings/profile': typeof ApproutesSettingsProfileRoute
  '/reset/$tokenId': typeof AuthroutesResetTokenIdRoute
  '/signup/$type': typeof AuthroutesSignupTypeRoute
  '/events/': typeof ApproutesEventsIndexRoute
  '/settings/': typeof ApproutesSettingsIndexRoute
  '/reset/': typeof AuthroutesResetIndexRoute
  '/signup/': typeof AuthroutesSignupIndexRoute
  '/onboarding/': typeof OnboardingroutesOnboardingIndexRoute
  '/school/$username/recruiting': typeof ApproutesSchoolUsernameRecruitingRoute
  '/school/$username/': typeof ApproutesSchoolUsernameIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof ApproutesIndexRoute
  '/dashboard': typeof AdminroutesDashboardRouteWithChildren
  '/$username': typeof ApproutesUsernameRoute
  '/explore': typeof ApproutesExploreRoute
  '/logout': typeof ApproutesLogoutRoute
  '/recruiting': typeof ApproutesRecruitingRoute
  '/resources': typeof ApproutesResourcesRoute
  '/unauthorized': typeof ApproutesUnauthorizedRoute
  '/login': typeof AuthroutesLoginRoute
  '/dashboard/assets': typeof AdminroutesDashboardAssetsRoute
  '/dashboard/metrics': typeof AdminroutesDashboardMetricsRoute
  '/events/$eventId': typeof ApproutesEventsEventIdRoute
  '/settings/general': typeof ApproutesSettingsGeneralRoute
  '/settings/media': typeof ApproutesSettingsMediaRoute
  '/settings/profile': typeof ApproutesSettingsProfileRoute
  '/reset/$tokenId': typeof AuthroutesResetTokenIdRoute
  '/signup/$type': typeof AuthroutesSignupTypeRoute
  '/events': typeof ApproutesEventsIndexRoute
  '/settings': typeof ApproutesSettingsIndexRoute
  '/reset': typeof AuthroutesResetIndexRoute
  '/signup': typeof AuthroutesSignupIndexRoute
  '/onboarding': typeof OnboardingroutesOnboardingIndexRoute
  '/school/$username/recruiting': typeof ApproutesSchoolUsernameRecruitingRoute
  '/school/$username': typeof ApproutesSchoolUsernameIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_admin': typeof AdminRouteRouteWithChildren
  '/_app': typeof AppRouteRouteWithChildren
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_onboarding': typeof OnboardingRouteRouteWithChildren
  '/_admin/(routes)/dashboard': typeof AdminroutesDashboardRouteWithChildren
  '/_app/(routes)/$username': typeof ApproutesUsernameRoute
  '/_app/(routes)/explore': typeof ApproutesExploreRoute
  '/_app/(routes)/logout': typeof ApproutesLogoutRoute
  '/_app/(routes)/recruiting': typeof ApproutesRecruitingRoute
  '/_app/(routes)/resources': typeof ApproutesResourcesRoute
  '/_app/(routes)/unauthorized': typeof ApproutesUnauthorizedRoute
  '/_auth/(routes)/login': typeof AuthroutesLoginRoute
  '/_app/(routes)/': typeof ApproutesIndexRoute
  '/_admin/(routes)/dashboard/assets': typeof AdminroutesDashboardAssetsRoute
  '/_admin/(routes)/dashboard/metrics': typeof AdminroutesDashboardMetricsRoute
  '/_app/(routes)/events/$eventId': typeof ApproutesEventsEventIdRoute
  '/_app/(routes)/settings/general': typeof ApproutesSettingsGeneralRoute
  '/_app/(routes)/settings/media': typeof ApproutesSettingsMediaRoute
  '/_app/(routes)/settings/profile': typeof ApproutesSettingsProfileRoute
  '/_auth/(routes)/reset/$tokenId': typeof AuthroutesResetTokenIdRoute
  '/_auth/(routes)/signup/$type': typeof AuthroutesSignupTypeRoute
  '/_app/(routes)/events/': typeof ApproutesEventsIndexRoute
  '/_app/(routes)/settings/': typeof ApproutesSettingsIndexRoute
  '/_auth/(routes)/reset/': typeof AuthroutesResetIndexRoute
  '/_auth/(routes)/signup/': typeof AuthroutesSignupIndexRoute
  '/_onboarding/(routes)/onboarding/': typeof OnboardingroutesOnboardingIndexRoute
  '/_app/(routes)/school/$username/recruiting': typeof ApproutesSchoolUsernameRecruitingRoute
  '/_app/(routes)/school/$username/': typeof ApproutesSchoolUsernameIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/$username'
    | '/explore'
    | '/logout'
    | '/recruiting'
    | '/resources'
    | '/unauthorized'
    | '/login'
    | '/dashboard/assets'
    | '/dashboard/metrics'
    | '/events/$eventId'
    | '/settings/general'
    | '/settings/media'
    | '/settings/profile'
    | '/reset/$tokenId'
    | '/signup/$type'
    | '/events/'
    | '/settings/'
    | '/reset/'
    | '/signup/'
    | '/onboarding/'
    | '/school/$username/recruiting'
    | '/school/$username/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/$username'
    | '/explore'
    | '/logout'
    | '/recruiting'
    | '/resources'
    | '/unauthorized'
    | '/login'
    | '/dashboard/assets'
    | '/dashboard/metrics'
    | '/events/$eventId'
    | '/settings/general'
    | '/settings/media'
    | '/settings/profile'
    | '/reset/$tokenId'
    | '/signup/$type'
    | '/events'
    | '/settings'
    | '/reset'
    | '/signup'
    | '/onboarding'
    | '/school/$username/recruiting'
    | '/school/$username'
  id:
    | '__root__'
    | '/_admin'
    | '/_app'
    | '/_auth'
    | '/_onboarding'
    | '/_admin/(routes)/dashboard'
    | '/_app/(routes)/$username'
    | '/_app/(routes)/explore'
    | '/_app/(routes)/logout'
    | '/_app/(routes)/recruiting'
    | '/_app/(routes)/resources'
    | '/_app/(routes)/unauthorized'
    | '/_auth/(routes)/login'
    | '/_app/(routes)/'
    | '/_admin/(routes)/dashboard/assets'
    | '/_admin/(routes)/dashboard/metrics'
    | '/_app/(routes)/events/$eventId'
    | '/_app/(routes)/settings/general'
    | '/_app/(routes)/settings/media'
    | '/_app/(routes)/settings/profile'
    | '/_auth/(routes)/reset/$tokenId'
    | '/_auth/(routes)/signup/$type'
    | '/_app/(routes)/events/'
    | '/_app/(routes)/settings/'
    | '/_auth/(routes)/reset/'
    | '/_auth/(routes)/signup/'
    | '/_onboarding/(routes)/onboarding/'
    | '/_app/(routes)/school/$username/recruiting'
    | '/_app/(routes)/school/$username/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  OnboardingRouteRoute: typeof OnboardingRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_onboarding': {
      id: '/_onboarding'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof OnboardingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/(routes)/': {
      id: '/_app/(routes)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ApproutesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_auth/(routes)/login': {
      id: '/_auth/(routes)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthroutesLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_app/(routes)/unauthorized': {
      id: '/_app/(routes)/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof ApproutesUnauthorizedRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/(routes)/resources': {
      id: '/_app/(routes)/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ApproutesResourcesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/(routes)/recruiting': {
      id: '/_app/(routes)/recruiting'
      path: '/recruiting'
      fullPath: '/recruiting'
      preLoaderRoute: typeof ApproutesRecruitingRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/(routes)/logout': {
      id: '/_app/(routes)/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof ApproutesLogoutRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/(routes)/explore': {
      id: '/_app/(routes)/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ApproutesExploreRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/(routes)/$username': {
      id: '/_app/(routes)/$username'
      path: '/$username'
      fullPath: '/$username'
      preLoaderRoute: typeof ApproutesUsernameRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_admin/(routes)/dashboard': {
      id: '/_admin/(routes)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AdminroutesDashboardRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_onboarding/(routes)/onboarding/': {
      id: '/_onboarding/(routes)/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingroutesOnboardingIndexRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/_auth/(routes)/signup/': {
      id: '/_auth/(routes)/signup/'
      path: '/signup'
      fullPath: '/signup/'
      preLoaderRoute: typeof AuthroutesSignupIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/(routes)/reset/': {
      id: '/_auth/(routes)/reset/'
      path: '/reset'
      fullPath: '/reset/'
      preLoaderRoute: typeof AuthroutesResetIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_app/(routes)/settings/': {
      id: '/_app/(routes)/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof ApproutesSettingsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/(routes)/events/': {
      id: '/_app/(routes)/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof ApproutesEventsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_auth/(routes)/signup/$type': {
      id: '/_auth/(routes)/signup/$type'
      path: '/signup/$type'
      fullPath: '/signup/$type'
      preLoaderRoute: typeof AuthroutesSignupTypeRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/(routes)/reset/$tokenId': {
      id: '/_auth/(routes)/reset/$tokenId'
      path: '/reset/$tokenId'
      fullPath: '/reset/$tokenId'
      preLoaderRoute: typeof AuthroutesResetTokenIdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_app/(routes)/settings/profile': {
      id: '/_app/(routes)/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof ApproutesSettingsProfileRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/(routes)/settings/media': {
      id: '/_app/(routes)/settings/media'
      path: '/settings/media'
      fullPath: '/settings/media'
      preLoaderRoute: typeof ApproutesSettingsMediaRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/(routes)/settings/general': {
      id: '/_app/(routes)/settings/general'
      path: '/settings/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof ApproutesSettingsGeneralRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/(routes)/events/$eventId': {
      id: '/_app/(routes)/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof ApproutesEventsEventIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_admin/(routes)/dashboard/metrics': {
      id: '/_admin/(routes)/dashboard/metrics'
      path: '/metrics'
      fullPath: '/dashboard/metrics'
      preLoaderRoute: typeof AdminroutesDashboardMetricsRouteImport
      parentRoute: typeof AdminroutesDashboardRoute
    }
    '/_admin/(routes)/dashboard/assets': {
      id: '/_admin/(routes)/dashboard/assets'
      path: '/assets'
      fullPath: '/dashboard/assets'
      preLoaderRoute: typeof AdminroutesDashboardAssetsRouteImport
      parentRoute: typeof AdminroutesDashboardRoute
    }
    '/_app/(routes)/school/$username/': {
      id: '/_app/(routes)/school/$username/'
      path: '/school/$username'
      fullPath: '/school/$username/'
      preLoaderRoute: typeof ApproutesSchoolUsernameIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/(routes)/school/$username/recruiting': {
      id: '/_app/(routes)/school/$username/recruiting'
      path: '/school/$username/recruiting'
      fullPath: '/school/$username/recruiting'
      preLoaderRoute: typeof ApproutesSchoolUsernameRecruitingRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AdminroutesDashboardRouteChildren {
  AdminroutesDashboardAssetsRoute: typeof AdminroutesDashboardAssetsRoute
  AdminroutesDashboardMetricsRoute: typeof AdminroutesDashboardMetricsRoute
}

const AdminroutesDashboardRouteChildren: AdminroutesDashboardRouteChildren = {
  AdminroutesDashboardAssetsRoute: AdminroutesDashboardAssetsRoute,
  AdminroutesDashboardMetricsRoute: AdminroutesDashboardMetricsRoute,
}

const AdminroutesDashboardRouteWithChildren =
  AdminroutesDashboardRoute._addFileChildren(AdminroutesDashboardRouteChildren)

interface AdminRouteRouteChildren {
  AdminroutesDashboardRoute: typeof AdminroutesDashboardRouteWithChildren
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminroutesDashboardRoute: AdminroutesDashboardRouteWithChildren,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface AppRouteRouteChildren {
  ApproutesUsernameRoute: typeof ApproutesUsernameRoute
  ApproutesExploreRoute: typeof ApproutesExploreRoute
  ApproutesLogoutRoute: typeof ApproutesLogoutRoute
  ApproutesRecruitingRoute: typeof ApproutesRecruitingRoute
  ApproutesResourcesRoute: typeof ApproutesResourcesRoute
  ApproutesUnauthorizedRoute: typeof ApproutesUnauthorizedRoute
  ApproutesIndexRoute: typeof ApproutesIndexRoute
  ApproutesEventsEventIdRoute: typeof ApproutesEventsEventIdRoute
  ApproutesSettingsGeneralRoute: typeof ApproutesSettingsGeneralRoute
  ApproutesSettingsMediaRoute: typeof ApproutesSettingsMediaRoute
  ApproutesSettingsProfileRoute: typeof ApproutesSettingsProfileRoute
  ApproutesEventsIndexRoute: typeof ApproutesEventsIndexRoute
  ApproutesSettingsIndexRoute: typeof ApproutesSettingsIndexRoute
  ApproutesSchoolUsernameRecruitingRoute: typeof ApproutesSchoolUsernameRecruitingRoute
  ApproutesSchoolUsernameIndexRoute: typeof ApproutesSchoolUsernameIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  ApproutesUsernameRoute: ApproutesUsernameRoute,
  ApproutesExploreRoute: ApproutesExploreRoute,
  ApproutesLogoutRoute: ApproutesLogoutRoute,
  ApproutesRecruitingRoute: ApproutesRecruitingRoute,
  ApproutesResourcesRoute: ApproutesResourcesRoute,
  ApproutesUnauthorizedRoute: ApproutesUnauthorizedRoute,
  ApproutesIndexRoute: ApproutesIndexRoute,
  ApproutesEventsEventIdRoute: ApproutesEventsEventIdRoute,
  ApproutesSettingsGeneralRoute: ApproutesSettingsGeneralRoute,
  ApproutesSettingsMediaRoute: ApproutesSettingsMediaRoute,
  ApproutesSettingsProfileRoute: ApproutesSettingsProfileRoute,
  ApproutesEventsIndexRoute: ApproutesEventsIndexRoute,
  ApproutesSettingsIndexRoute: ApproutesSettingsIndexRoute,
  ApproutesSchoolUsernameRecruitingRoute:
    ApproutesSchoolUsernameRecruitingRoute,
  ApproutesSchoolUsernameIndexRoute: ApproutesSchoolUsernameIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthroutesLoginRoute: typeof AuthroutesLoginRoute
  AuthroutesResetTokenIdRoute: typeof AuthroutesResetTokenIdRoute
  AuthroutesSignupTypeRoute: typeof AuthroutesSignupTypeRoute
  AuthroutesResetIndexRoute: typeof AuthroutesResetIndexRoute
  AuthroutesSignupIndexRoute: typeof AuthroutesSignupIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthroutesLoginRoute: AuthroutesLoginRoute,
  AuthroutesResetTokenIdRoute: AuthroutesResetTokenIdRoute,
  AuthroutesSignupTypeRoute: AuthroutesSignupTypeRoute,
  AuthroutesResetIndexRoute: AuthroutesResetIndexRoute,
  AuthroutesSignupIndexRoute: AuthroutesSignupIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface OnboardingRouteRouteChildren {
  OnboardingroutesOnboardingIndexRoute: typeof OnboardingroutesOnboardingIndexRoute
}

const OnboardingRouteRouteChildren: OnboardingRouteRouteChildren = {
  OnboardingroutesOnboardingIndexRoute: OnboardingroutesOnboardingIndexRoute,
}

const OnboardingRouteRouteWithChildren = OnboardingRouteRoute._addFileChildren(
  OnboardingRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  OnboardingRouteRoute: OnboardingRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
