/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteRouteImport } from './routes/_onboarding/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AdminRouteRouteImport } from './routes/_admin/route'
import { Route as ApproutesIndexRouteImport } from './routes/_app/(routes)/index'
import { Route as AuthroutesLoginRouteImport } from './routes/_auth/(routes)/login'
import { Route as ApproutesUnauthorizedRouteImport } from './routes/_app/(routes)/unauthorized'
import { Route as ApproutesLogoutRouteImport } from './routes/_app/(routes)/logout'
import { Route as ApproutesFeedRouteImport } from './routes/_app/(routes)/feed'
import { Route as ApproutesUsernameRouteImport } from './routes/_app/(routes)/$username'
import { Route as AdminroutesDashboardRouteImport } from './routes/_admin/(routes)/dashboard'
import { Route as ApproutesResourcesRouteRouteImport } from './routes/_app/(routes)/resources/route'
import { Route as ApproutesRecruitingRouteRouteImport } from './routes/_app/(routes)/recruiting/route'
import { Route as OnboardingroutesOnboardingIndexRouteImport } from './routes/_onboarding/(routes)/onboarding/index'
import { Route as AuthroutesSignupIndexRouteImport } from './routes/_auth/(routes)/signup/index'
import { Route as AuthroutesResetIndexRouteImport } from './routes/_auth/(routes)/reset/index'
import { Route as ApproutesSettingsIndexRouteImport } from './routes/_app/(routes)/settings/index'
import { Route as ApproutesResourcesIndexRouteImport } from './routes/_app/(routes)/resources/index'
import { Route as ApproutesRecruitingIndexRouteImport } from './routes/_app/(routes)/recruiting/index'
import { Route as ApproutesExploreIndexRouteImport } from './routes/_app/(routes)/explore/index'
import { Route as ApproutesEventsIndexRouteImport } from './routes/_app/(routes)/events/index'
import { Route as AuthroutesSignupTypeRouteImport } from './routes/_auth/(routes)/signup/$type'
import { Route as AuthroutesResetTokenIdRouteImport } from './routes/_auth/(routes)/reset/$tokenId'
import { Route as ApproutesSettingsProfileRouteImport } from './routes/_app/(routes)/settings/profile'
import { Route as ApproutesSettingsMediaRouteImport } from './routes/_app/(routes)/settings/media'
import { Route as ApproutesSettingsGeneralRouteImport } from './routes/_app/(routes)/settings/general'
import { Route as ApproutesResourcesLibraryRouteImport } from './routes/_app/(routes)/resources/library'
import { Route as ApproutesResourcesBlogRouteImport } from './routes/_app/(routes)/resources/blog'
import { Route as ApproutesRecruitingSubmitRouteImport } from './routes/_app/(routes)/recruiting/submit'
import { Route as ApproutesRecruitingEditRouteImport } from './routes/_app/(routes)/recruiting/edit'
import { Route as ApproutesExploreUsernameRouteImport } from './routes/_app/(routes)/explore/$username'
import { Route as ApproutesEventsEventIdRouteImport } from './routes/_app/(routes)/events/$eventId'
import { Route as AdminroutesDashboardMetricsRouteImport } from './routes/_admin/(routes)/dashboard/metrics'
import { Route as AdminroutesDashboardAssetsRouteImport } from './routes/_admin/(routes)/dashboard/assets'

const OnboardingRouteRoute = OnboardingRouteRouteImport.update({
  id: '/_onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApproutesIndexRoute = ApproutesIndexRouteImport.update({
  id: '/(routes)/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AuthroutesLoginRoute = AuthroutesLoginRouteImport.update({
  id: '/(routes)/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ApproutesUnauthorizedRoute = ApproutesUnauthorizedRouteImport.update({
  id: '/(routes)/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApproutesLogoutRoute = ApproutesLogoutRouteImport.update({
  id: '/(routes)/logout',
  path: '/logout',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApproutesFeedRoute = ApproutesFeedRouteImport.update({
  id: '/(routes)/feed',
  path: '/feed',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApproutesUsernameRoute = ApproutesUsernameRouteImport.update({
  id: '/(routes)/$username',
  path: '/$username',
  getParentRoute: () => AppRouteRoute,
} as any)
const AdminroutesDashboardRoute = AdminroutesDashboardRouteImport.update({
  id: '/(routes)/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ApproutesResourcesRouteRoute = ApproutesResourcesRouteRouteImport.update({
  id: '/(routes)/resources',
  path: '/resources',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApproutesRecruitingRouteRoute =
  ApproutesRecruitingRouteRouteImport.update({
    id: '/(routes)/recruiting',
    path: '/recruiting',
    getParentRoute: () => AppRouteRoute,
  } as any)
const OnboardingroutesOnboardingIndexRoute =
  OnboardingroutesOnboardingIndexRouteImport.update({
    id: '/(routes)/onboarding/',
    path: '/onboarding/',
    getParentRoute: () => OnboardingRouteRoute,
  } as any)
const AuthroutesSignupIndexRoute = AuthroutesSignupIndexRouteImport.update({
  id: '/(routes)/signup/',
  path: '/signup/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthroutesResetIndexRoute = AuthroutesResetIndexRouteImport.update({
  id: '/(routes)/reset/',
  path: '/reset/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ApproutesSettingsIndexRoute = ApproutesSettingsIndexRouteImport.update({
  id: '/(routes)/settings/',
  path: '/settings/',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApproutesResourcesIndexRoute = ApproutesResourcesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ApproutesResourcesRouteRoute,
} as any)
const ApproutesRecruitingIndexRoute =
  ApproutesRecruitingIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ApproutesRecruitingRouteRoute,
  } as any)
const ApproutesExploreIndexRoute = ApproutesExploreIndexRouteImport.update({
  id: '/(routes)/explore/',
  path: '/explore/',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApproutesEventsIndexRoute = ApproutesEventsIndexRouteImport.update({
  id: '/(routes)/events/',
  path: '/events/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AuthroutesSignupTypeRoute = AuthroutesSignupTypeRouteImport.update({
  id: '/(routes)/signup/$type',
  path: '/signup/$type',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthroutesResetTokenIdRoute = AuthroutesResetTokenIdRouteImport.update({
  id: '/(routes)/reset/$tokenId',
  path: '/reset/$tokenId',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ApproutesSettingsProfileRoute =
  ApproutesSettingsProfileRouteImport.update({
    id: '/(routes)/settings/profile',
    path: '/settings/profile',
    getParentRoute: () => AppRouteRoute,
  } as any)
const ApproutesSettingsMediaRoute = ApproutesSettingsMediaRouteImport.update({
  id: '/(routes)/settings/media',
  path: '/settings/media',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApproutesSettingsGeneralRoute =
  ApproutesSettingsGeneralRouteImport.update({
    id: '/(routes)/settings/general',
    path: '/settings/general',
    getParentRoute: () => AppRouteRoute,
  } as any)
const ApproutesResourcesLibraryRoute =
  ApproutesResourcesLibraryRouteImport.update({
    id: '/library',
    path: '/library',
    getParentRoute: () => ApproutesResourcesRouteRoute,
  } as any)
const ApproutesResourcesBlogRoute = ApproutesResourcesBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => ApproutesResourcesRouteRoute,
} as any)
const ApproutesRecruitingSubmitRoute =
  ApproutesRecruitingSubmitRouteImport.update({
    id: '/submit',
    path: '/submit',
    getParentRoute: () => ApproutesRecruitingRouteRoute,
  } as any)
const ApproutesRecruitingEditRoute = ApproutesRecruitingEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ApproutesRecruitingRouteRoute,
} as any)
const ApproutesExploreUsernameRoute =
  ApproutesExploreUsernameRouteImport.update({
    id: '/(routes)/explore/$username',
    path: '/explore/$username',
    getParentRoute: () => AppRouteRoute,
  } as any)
const ApproutesEventsEventIdRoute = ApproutesEventsEventIdRouteImport.update({
  id: '/(routes)/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AdminroutesDashboardMetricsRoute =
  AdminroutesDashboardMetricsRouteImport.update({
    id: '/metrics',
    path: '/metrics',
    getParentRoute: () => AdminroutesDashboardRoute,
  } as any)
const AdminroutesDashboardAssetsRoute =
  AdminroutesDashboardAssetsRouteImport.update({
    id: '/assets',
    path: '/assets',
    getParentRoute: () => AdminroutesDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ApproutesIndexRoute
  '/recruiting': typeof ApproutesRecruitingRouteRouteWithChildren
  '/resources': typeof ApproutesResourcesRouteRouteWithChildren
  '/dashboard': typeof AdminroutesDashboardRouteWithChildren
  '/$username': typeof ApproutesUsernameRoute
  '/feed': typeof ApproutesFeedRoute
  '/logout': typeof ApproutesLogoutRoute
  '/unauthorized': typeof ApproutesUnauthorizedRoute
  '/login': typeof AuthroutesLoginRoute
  '/dashboard/assets': typeof AdminroutesDashboardAssetsRoute
  '/dashboard/metrics': typeof AdminroutesDashboardMetricsRoute
  '/events/$eventId': typeof ApproutesEventsEventIdRoute
  '/explore/$username': typeof ApproutesExploreUsernameRoute
  '/recruiting/edit': typeof ApproutesRecruitingEditRoute
  '/recruiting/submit': typeof ApproutesRecruitingSubmitRoute
  '/resources/blog': typeof ApproutesResourcesBlogRoute
  '/resources/library': typeof ApproutesResourcesLibraryRoute
  '/settings/general': typeof ApproutesSettingsGeneralRoute
  '/settings/media': typeof ApproutesSettingsMediaRoute
  '/settings/profile': typeof ApproutesSettingsProfileRoute
  '/reset/$tokenId': typeof AuthroutesResetTokenIdRoute
  '/signup/$type': typeof AuthroutesSignupTypeRoute
  '/events/': typeof ApproutesEventsIndexRoute
  '/explore/': typeof ApproutesExploreIndexRoute
  '/recruiting/': typeof ApproutesRecruitingIndexRoute
  '/resources/': typeof ApproutesResourcesIndexRoute
  '/settings/': typeof ApproutesSettingsIndexRoute
  '/reset/': typeof AuthroutesResetIndexRoute
  '/signup/': typeof AuthroutesSignupIndexRoute
  '/onboarding/': typeof OnboardingroutesOnboardingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof ApproutesIndexRoute
  '/dashboard': typeof AdminroutesDashboardRouteWithChildren
  '/$username': typeof ApproutesUsernameRoute
  '/feed': typeof ApproutesFeedRoute
  '/logout': typeof ApproutesLogoutRoute
  '/unauthorized': typeof ApproutesUnauthorizedRoute
  '/login': typeof AuthroutesLoginRoute
  '/dashboard/assets': typeof AdminroutesDashboardAssetsRoute
  '/dashboard/metrics': typeof AdminroutesDashboardMetricsRoute
  '/events/$eventId': typeof ApproutesEventsEventIdRoute
  '/explore/$username': typeof ApproutesExploreUsernameRoute
  '/recruiting/edit': typeof ApproutesRecruitingEditRoute
  '/recruiting/submit': typeof ApproutesRecruitingSubmitRoute
  '/resources/blog': typeof ApproutesResourcesBlogRoute
  '/resources/library': typeof ApproutesResourcesLibraryRoute
  '/settings/general': typeof ApproutesSettingsGeneralRoute
  '/settings/media': typeof ApproutesSettingsMediaRoute
  '/settings/profile': typeof ApproutesSettingsProfileRoute
  '/reset/$tokenId': typeof AuthroutesResetTokenIdRoute
  '/signup/$type': typeof AuthroutesSignupTypeRoute
  '/events': typeof ApproutesEventsIndexRoute
  '/explore': typeof ApproutesExploreIndexRoute
  '/recruiting': typeof ApproutesRecruitingIndexRoute
  '/resources': typeof ApproutesResourcesIndexRoute
  '/settings': typeof ApproutesSettingsIndexRoute
  '/reset': typeof AuthroutesResetIndexRoute
  '/signup': typeof AuthroutesSignupIndexRoute
  '/onboarding': typeof OnboardingroutesOnboardingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_admin': typeof AdminRouteRouteWithChildren
  '/_app': typeof AppRouteRouteWithChildren
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_onboarding': typeof OnboardingRouteRouteWithChildren
  '/_app/(routes)/recruiting': typeof ApproutesRecruitingRouteRouteWithChildren
  '/_app/(routes)/resources': typeof ApproutesResourcesRouteRouteWithChildren
  '/_admin/(routes)/dashboard': typeof AdminroutesDashboardRouteWithChildren
  '/_app/(routes)/$username': typeof ApproutesUsernameRoute
  '/_app/(routes)/feed': typeof ApproutesFeedRoute
  '/_app/(routes)/logout': typeof ApproutesLogoutRoute
  '/_app/(routes)/unauthorized': typeof ApproutesUnauthorizedRoute
  '/_auth/(routes)/login': typeof AuthroutesLoginRoute
  '/_app/(routes)/': typeof ApproutesIndexRoute
  '/_admin/(routes)/dashboard/assets': typeof AdminroutesDashboardAssetsRoute
  '/_admin/(routes)/dashboard/metrics': typeof AdminroutesDashboardMetricsRoute
  '/_app/(routes)/events/$eventId': typeof ApproutesEventsEventIdRoute
  '/_app/(routes)/explore/$username': typeof ApproutesExploreUsernameRoute
  '/_app/(routes)/recruiting/edit': typeof ApproutesRecruitingEditRoute
  '/_app/(routes)/recruiting/submit': typeof ApproutesRecruitingSubmitRoute
  '/_app/(routes)/resources/blog': typeof ApproutesResourcesBlogRoute
  '/_app/(routes)/resources/library': typeof ApproutesResourcesLibraryRoute
  '/_app/(routes)/settings/general': typeof ApproutesSettingsGeneralRoute
  '/_app/(routes)/settings/media': typeof ApproutesSettingsMediaRoute
  '/_app/(routes)/settings/profile': typeof ApproutesSettingsProfileRoute
  '/_auth/(routes)/reset/$tokenId': typeof AuthroutesResetTokenIdRoute
  '/_auth/(routes)/signup/$type': typeof AuthroutesSignupTypeRoute
  '/_app/(routes)/events/': typeof ApproutesEventsIndexRoute
  '/_app/(routes)/explore/': typeof ApproutesExploreIndexRoute
  '/_app/(routes)/recruiting/': typeof ApproutesRecruitingIndexRoute
  '/_app/(routes)/resources/': typeof ApproutesResourcesIndexRoute
  '/_app/(routes)/settings/': typeof ApproutesSettingsIndexRoute
  '/_auth/(routes)/reset/': typeof AuthroutesResetIndexRoute
  '/_auth/(routes)/signup/': typeof AuthroutesSignupIndexRoute
  '/_onboarding/(routes)/onboarding/': typeof OnboardingroutesOnboardingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/recruiting'
    | '/resources'
    | '/dashboard'
    | '/$username'
    | '/feed'
    | '/logout'
    | '/unauthorized'
    | '/login'
    | '/dashboard/assets'
    | '/dashboard/metrics'
    | '/events/$eventId'
    | '/explore/$username'
    | '/recruiting/edit'
    | '/recruiting/submit'
    | '/resources/blog'
    | '/resources/library'
    | '/settings/general'
    | '/settings/media'
    | '/settings/profile'
    | '/reset/$tokenId'
    | '/signup/$type'
    | '/events/'
    | '/explore/'
    | '/recruiting/'
    | '/resources/'
    | '/settings/'
    | '/reset/'
    | '/signup/'
    | '/onboarding/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/$username'
    | '/feed'
    | '/logout'
    | '/unauthorized'
    | '/login'
    | '/dashboard/assets'
    | '/dashboard/metrics'
    | '/events/$eventId'
    | '/explore/$username'
    | '/recruiting/edit'
    | '/recruiting/submit'
    | '/resources/blog'
    | '/resources/library'
    | '/settings/general'
    | '/settings/media'
    | '/settings/profile'
    | '/reset/$tokenId'
    | '/signup/$type'
    | '/events'
    | '/explore'
    | '/recruiting'
    | '/resources'
    | '/settings'
    | '/reset'
    | '/signup'
    | '/onboarding'
  id:
    | '__root__'
    | '/_admin'
    | '/_app'
    | '/_auth'
    | '/_onboarding'
    | '/_app/(routes)/recruiting'
    | '/_app/(routes)/resources'
    | '/_admin/(routes)/dashboard'
    | '/_app/(routes)/$username'
    | '/_app/(routes)/feed'
    | '/_app/(routes)/logout'
    | '/_app/(routes)/unauthorized'
    | '/_auth/(routes)/login'
    | '/_app/(routes)/'
    | '/_admin/(routes)/dashboard/assets'
    | '/_admin/(routes)/dashboard/metrics'
    | '/_app/(routes)/events/$eventId'
    | '/_app/(routes)/explore/$username'
    | '/_app/(routes)/recruiting/edit'
    | '/_app/(routes)/recruiting/submit'
    | '/_app/(routes)/resources/blog'
    | '/_app/(routes)/resources/library'
    | '/_app/(routes)/settings/general'
    | '/_app/(routes)/settings/media'
    | '/_app/(routes)/settings/profile'
    | '/_auth/(routes)/reset/$tokenId'
    | '/_auth/(routes)/signup/$type'
    | '/_app/(routes)/events/'
    | '/_app/(routes)/explore/'
    | '/_app/(routes)/recruiting/'
    | '/_app/(routes)/resources/'
    | '/_app/(routes)/settings/'
    | '/_auth/(routes)/reset/'
    | '/_auth/(routes)/signup/'
    | '/_onboarding/(routes)/onboarding/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  OnboardingRouteRoute: typeof OnboardingRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_onboarding': {
      id: '/_onboarding'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof OnboardingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/(routes)/': {
      id: '/_app/(routes)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ApproutesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_auth/(routes)/login': {
      id: '/_auth/(routes)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthroutesLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_app/(routes)/unauthorized': {
      id: '/_app/(routes)/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof ApproutesUnauthorizedRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/(routes)/logout': {
      id: '/_app/(routes)/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof ApproutesLogoutRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/(routes)/feed': {
      id: '/_app/(routes)/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof ApproutesFeedRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/(routes)/$username': {
      id: '/_app/(routes)/$username'
      path: '/$username'
      fullPath: '/$username'
      preLoaderRoute: typeof ApproutesUsernameRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_admin/(routes)/dashboard': {
      id: '/_admin/(routes)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AdminroutesDashboardRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_app/(routes)/resources': {
      id: '/_app/(routes)/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ApproutesResourcesRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/(routes)/recruiting': {
      id: '/_app/(routes)/recruiting'
      path: '/recruiting'
      fullPath: '/recruiting'
      preLoaderRoute: typeof ApproutesRecruitingRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_onboarding/(routes)/onboarding/': {
      id: '/_onboarding/(routes)/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingroutesOnboardingIndexRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/_auth/(routes)/signup/': {
      id: '/_auth/(routes)/signup/'
      path: '/signup'
      fullPath: '/signup/'
      preLoaderRoute: typeof AuthroutesSignupIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/(routes)/reset/': {
      id: '/_auth/(routes)/reset/'
      path: '/reset'
      fullPath: '/reset/'
      preLoaderRoute: typeof AuthroutesResetIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_app/(routes)/settings/': {
      id: '/_app/(routes)/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof ApproutesSettingsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/(routes)/resources/': {
      id: '/_app/(routes)/resources/'
      path: '/'
      fullPath: '/resources/'
      preLoaderRoute: typeof ApproutesResourcesIndexRouteImport
      parentRoute: typeof ApproutesResourcesRouteRoute
    }
    '/_app/(routes)/recruiting/': {
      id: '/_app/(routes)/recruiting/'
      path: '/'
      fullPath: '/recruiting/'
      preLoaderRoute: typeof ApproutesRecruitingIndexRouteImport
      parentRoute: typeof ApproutesRecruitingRouteRoute
    }
    '/_app/(routes)/explore/': {
      id: '/_app/(routes)/explore/'
      path: '/explore'
      fullPath: '/explore/'
      preLoaderRoute: typeof ApproutesExploreIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/(routes)/events/': {
      id: '/_app/(routes)/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof ApproutesEventsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_auth/(routes)/signup/$type': {
      id: '/_auth/(routes)/signup/$type'
      path: '/signup/$type'
      fullPath: '/signup/$type'
      preLoaderRoute: typeof AuthroutesSignupTypeRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/(routes)/reset/$tokenId': {
      id: '/_auth/(routes)/reset/$tokenId'
      path: '/reset/$tokenId'
      fullPath: '/reset/$tokenId'
      preLoaderRoute: typeof AuthroutesResetTokenIdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_app/(routes)/settings/profile': {
      id: '/_app/(routes)/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof ApproutesSettingsProfileRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/(routes)/settings/media': {
      id: '/_app/(routes)/settings/media'
      path: '/settings/media'
      fullPath: '/settings/media'
      preLoaderRoute: typeof ApproutesSettingsMediaRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/(routes)/settings/general': {
      id: '/_app/(routes)/settings/general'
      path: '/settings/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof ApproutesSettingsGeneralRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/(routes)/resources/library': {
      id: '/_app/(routes)/resources/library'
      path: '/library'
      fullPath: '/resources/library'
      preLoaderRoute: typeof ApproutesResourcesLibraryRouteImport
      parentRoute: typeof ApproutesResourcesRouteRoute
    }
    '/_app/(routes)/resources/blog': {
      id: '/_app/(routes)/resources/blog'
      path: '/blog'
      fullPath: '/resources/blog'
      preLoaderRoute: typeof ApproutesResourcesBlogRouteImport
      parentRoute: typeof ApproutesResourcesRouteRoute
    }
    '/_app/(routes)/recruiting/submit': {
      id: '/_app/(routes)/recruiting/submit'
      path: '/submit'
      fullPath: '/recruiting/submit'
      preLoaderRoute: typeof ApproutesRecruitingSubmitRouteImport
      parentRoute: typeof ApproutesRecruitingRouteRoute
    }
    '/_app/(routes)/recruiting/edit': {
      id: '/_app/(routes)/recruiting/edit'
      path: '/edit'
      fullPath: '/recruiting/edit'
      preLoaderRoute: typeof ApproutesRecruitingEditRouteImport
      parentRoute: typeof ApproutesRecruitingRouteRoute
    }
    '/_app/(routes)/explore/$username': {
      id: '/_app/(routes)/explore/$username'
      path: '/explore/$username'
      fullPath: '/explore/$username'
      preLoaderRoute: typeof ApproutesExploreUsernameRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/(routes)/events/$eventId': {
      id: '/_app/(routes)/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof ApproutesEventsEventIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_admin/(routes)/dashboard/metrics': {
      id: '/_admin/(routes)/dashboard/metrics'
      path: '/metrics'
      fullPath: '/dashboard/metrics'
      preLoaderRoute: typeof AdminroutesDashboardMetricsRouteImport
      parentRoute: typeof AdminroutesDashboardRoute
    }
    '/_admin/(routes)/dashboard/assets': {
      id: '/_admin/(routes)/dashboard/assets'
      path: '/assets'
      fullPath: '/dashboard/assets'
      preLoaderRoute: typeof AdminroutesDashboardAssetsRouteImport
      parentRoute: typeof AdminroutesDashboardRoute
    }
  }
}

interface AdminroutesDashboardRouteChildren {
  AdminroutesDashboardAssetsRoute: typeof AdminroutesDashboardAssetsRoute
  AdminroutesDashboardMetricsRoute: typeof AdminroutesDashboardMetricsRoute
}

const AdminroutesDashboardRouteChildren: AdminroutesDashboardRouteChildren = {
  AdminroutesDashboardAssetsRoute: AdminroutesDashboardAssetsRoute,
  AdminroutesDashboardMetricsRoute: AdminroutesDashboardMetricsRoute,
}

const AdminroutesDashboardRouteWithChildren =
  AdminroutesDashboardRoute._addFileChildren(AdminroutesDashboardRouteChildren)

interface AdminRouteRouteChildren {
  AdminroutesDashboardRoute: typeof AdminroutesDashboardRouteWithChildren
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminroutesDashboardRoute: AdminroutesDashboardRouteWithChildren,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface ApproutesRecruitingRouteRouteChildren {
  ApproutesRecruitingEditRoute: typeof ApproutesRecruitingEditRoute
  ApproutesRecruitingSubmitRoute: typeof ApproutesRecruitingSubmitRoute
  ApproutesRecruitingIndexRoute: typeof ApproutesRecruitingIndexRoute
}

const ApproutesRecruitingRouteRouteChildren: ApproutesRecruitingRouteRouteChildren =
  {
    ApproutesRecruitingEditRoute: ApproutesRecruitingEditRoute,
    ApproutesRecruitingSubmitRoute: ApproutesRecruitingSubmitRoute,
    ApproutesRecruitingIndexRoute: ApproutesRecruitingIndexRoute,
  }

const ApproutesRecruitingRouteRouteWithChildren =
  ApproutesRecruitingRouteRoute._addFileChildren(
    ApproutesRecruitingRouteRouteChildren,
  )

interface ApproutesResourcesRouteRouteChildren {
  ApproutesResourcesBlogRoute: typeof ApproutesResourcesBlogRoute
  ApproutesResourcesLibraryRoute: typeof ApproutesResourcesLibraryRoute
  ApproutesResourcesIndexRoute: typeof ApproutesResourcesIndexRoute
}

const ApproutesResourcesRouteRouteChildren: ApproutesResourcesRouteRouteChildren =
  {
    ApproutesResourcesBlogRoute: ApproutesResourcesBlogRoute,
    ApproutesResourcesLibraryRoute: ApproutesResourcesLibraryRoute,
    ApproutesResourcesIndexRoute: ApproutesResourcesIndexRoute,
  }

const ApproutesResourcesRouteRouteWithChildren =
  ApproutesResourcesRouteRoute._addFileChildren(
    ApproutesResourcesRouteRouteChildren,
  )

interface AppRouteRouteChildren {
  ApproutesRecruitingRouteRoute: typeof ApproutesRecruitingRouteRouteWithChildren
  ApproutesResourcesRouteRoute: typeof ApproutesResourcesRouteRouteWithChildren
  ApproutesUsernameRoute: typeof ApproutesUsernameRoute
  ApproutesFeedRoute: typeof ApproutesFeedRoute
  ApproutesLogoutRoute: typeof ApproutesLogoutRoute
  ApproutesUnauthorizedRoute: typeof ApproutesUnauthorizedRoute
  ApproutesIndexRoute: typeof ApproutesIndexRoute
  ApproutesEventsEventIdRoute: typeof ApproutesEventsEventIdRoute
  ApproutesExploreUsernameRoute: typeof ApproutesExploreUsernameRoute
  ApproutesSettingsGeneralRoute: typeof ApproutesSettingsGeneralRoute
  ApproutesSettingsMediaRoute: typeof ApproutesSettingsMediaRoute
  ApproutesSettingsProfileRoute: typeof ApproutesSettingsProfileRoute
  ApproutesEventsIndexRoute: typeof ApproutesEventsIndexRoute
  ApproutesExploreIndexRoute: typeof ApproutesExploreIndexRoute
  ApproutesSettingsIndexRoute: typeof ApproutesSettingsIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  ApproutesRecruitingRouteRoute: ApproutesRecruitingRouteRouteWithChildren,
  ApproutesResourcesRouteRoute: ApproutesResourcesRouteRouteWithChildren,
  ApproutesUsernameRoute: ApproutesUsernameRoute,
  ApproutesFeedRoute: ApproutesFeedRoute,
  ApproutesLogoutRoute: ApproutesLogoutRoute,
  ApproutesUnauthorizedRoute: ApproutesUnauthorizedRoute,
  ApproutesIndexRoute: ApproutesIndexRoute,
  ApproutesEventsEventIdRoute: ApproutesEventsEventIdRoute,
  ApproutesExploreUsernameRoute: ApproutesExploreUsernameRoute,
  ApproutesSettingsGeneralRoute: ApproutesSettingsGeneralRoute,
  ApproutesSettingsMediaRoute: ApproutesSettingsMediaRoute,
  ApproutesSettingsProfileRoute: ApproutesSettingsProfileRoute,
  ApproutesEventsIndexRoute: ApproutesEventsIndexRoute,
  ApproutesExploreIndexRoute: ApproutesExploreIndexRoute,
  ApproutesSettingsIndexRoute: ApproutesSettingsIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthroutesLoginRoute: typeof AuthroutesLoginRoute
  AuthroutesResetTokenIdRoute: typeof AuthroutesResetTokenIdRoute
  AuthroutesSignupTypeRoute: typeof AuthroutesSignupTypeRoute
  AuthroutesResetIndexRoute: typeof AuthroutesResetIndexRoute
  AuthroutesSignupIndexRoute: typeof AuthroutesSignupIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthroutesLoginRoute: AuthroutesLoginRoute,
  AuthroutesResetTokenIdRoute: AuthroutesResetTokenIdRoute,
  AuthroutesSignupTypeRoute: AuthroutesSignupTypeRoute,
  AuthroutesResetIndexRoute: AuthroutesResetIndexRoute,
  AuthroutesSignupIndexRoute: AuthroutesSignupIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface OnboardingRouteRouteChildren {
  OnboardingroutesOnboardingIndexRoute: typeof OnboardingroutesOnboardingIndexRoute
}

const OnboardingRouteRouteChildren: OnboardingRouteRouteChildren = {
  OnboardingroutesOnboardingIndexRoute: OnboardingroutesOnboardingIndexRoute,
}

const OnboardingRouteRouteWithChildren = OnboardingRouteRoute._addFileChildren(
  OnboardingRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  OnboardingRouteRoute: OnboardingRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
