/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create user account
         * @description Creates a new base user account.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["AuthSignupRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthSignupResponse"];
                    };
                };
                /** @description Unprocessable Entity */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start user session
         * @description Logs in a user and creates a session in Redis.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["AuthLoginRequest"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unprocessable Entity */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Too Many Requests */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * End user session
         * @description Logs out the current user and deletes their session from Redis.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthLogoutResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get user session
         * @description Retrieves the current session's user information.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthSessionResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dancers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a dancer
         * @description Populate account with personal information to finish dancer signup
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["DancersRequest"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unprocessable Entity */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HealthResponse"];
                    };
                };
                /** @description Service Unavailable */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HealthResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schools/filters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get school filters
         * @description Returns the filters to use when searching for schools
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SchoolsFiltersResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/check-availability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check username availability
         * @description Checks if a username is available for registration.
         */
        get: {
            parameters: {
                query: {
                    username: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UsersCheckavailabilityResponse"];
                    };
                };
                /** @description Unprocessable Entity */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/filters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get explore filters
         * @description Returns the filters to use when searching for users (requires type)
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UsersFiltersResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            /** @description Human-readable error message suitable for display */
            message: string;
            /**
             * @description Machine-readable error code for programmatic handling
             * @example E_BAD_REQUEST
             */
            code: string;
            /**
             * @description HTTP status code returned by the server
             * @example 429
             */
            status: number;
            /**
             * @description Seconds until the request can be retried
             * @example 60
             */
            retryAfter?: number;
            /** @description Additional context specific to the validation error */
            errors?: components["schemas"]["ValidationError"][];
            /**
             * @description Additional context specific to the error type
             * @example {
             *       "userId": "123"
             *     }
             */
            meta?: {
                [key: string]: unknown;
            };
        };
        ValidationError: {
            /**
             * @description Validation error field name
             * @example email
             */
            field: string;
            /**
             * @description Validation error message
             * @example Email is required
             */
            message: string;
        };
        /** @enum {string} */
        Role: "admin" | "user" | "prodigy_admin";
        /** @enum {string} */
        AccountType: "dancer" | "school";
        /** @enum {string} */
        PlatformName: "prodigy" | "core";
        AuthSignupRequest: {
            phone?: string | null;
            email: string;
            password: string;
            type: components["schemas"]["AccountType"];
            username: string;
            firstName: string;
            lastName: string;
            termsChecked: boolean;
        };
        AuthSignupResponse: {
            email: string;
            username: string;
            id: string;
            role: components["schemas"]["Role"];
            avatar: string | null;
            displayEmail: string;
            firstName: string;
            lastName: string;
        };
        AuthLoginRequest: {
            email: string;
            password: string;
        };
        AuthLogoutResponse: {
            message: string;
        };
        AuthSessionResponse: {
            email: string;
            type: components["schemas"]["AccountType"];
            username: string;
            platforms: components["schemas"]["PlatformName"][];
            id: string;
            role: components["schemas"]["Role"];
            avatar: string | null;
            displayEmail: string;
            subscribed: boolean;
        };
        DancersRequest: {
            phoneNumber?: string | null;
            birthday: string | number;
            location: string;
            platform: components["schemas"]["PlatformName"];
        };
        HealthResponse: {
            isHealthy: boolean;
            /** @enum {string} */
            status: "error" | "ok" | "warning";
            finishedAt: string;
            debugInfo: {
                pid: number;
                ppid?: number;
                uptime: number;
                version: string;
                platform: string;
            };
            checks: {
                name: string;
                meta?: Record<string, never>;
                message: string;
                /** @enum {string} */
                status: "error" | "ok" | "warning";
                finishedAt: string;
                isCached: boolean;
            }[];
        };
        SchoolsFiltersResponse: ({
            type: string;
            id: string;
            label: string;
            paramKey: string;
        } | {
            type: string;
            id: string;
            options: {
                label: string;
                value: string;
            }[];
            label: string;
            paramKey: string;
        })[];
        UsersCheckavailabilityResponse: {
            available: boolean;
        };
        UsersFiltersResponse: ({
            type: string;
            id: string;
            label: string;
            paramKey: string;
        } | {
            type: string;
            id: string;
            options: {
                label: string;
                value: string;
            }[];
            label: string;
            paramKey: string;
        })[];
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
